"SBRC  	R15, 3"          "\n\t"
"WDR   	"                "\n\t"
"FMULS 	R16, R17"        "\n\t"
"STS   	2162, R27"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"OR    	R29, R5"         "\n\t"
"SBCI  	R18, 5"          "\n\t"
"BLD   	R6, 6"           "\n\t"
"CPI   	R23, 49"         "\n\t"
"SWAP  	R7"              "\n\t"
"SUBI  	R19, 158"        "\n\t"
"ADIW  	R30, 28"         "\n\t"
"LDD   	R7, Z+2"         "\n\t"
"SBCI  	R26, 90"         "\n\t"
"WDR   	"                "\n\t"
"CBI   	24, 1"           "\n\t"
"NEG   	R11"             "\n\t"
"LDS   	R17, 1524"       "\n\t"
"MULSU 	R20, R16"        "\n\t"
"BST   	R0, 3"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LSR   	R11"             "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBIC  	19, 0"           "\n\t"
"ANDI  	R16, 75"         "\n\t"
"LDD   	R17, Z+48"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"ASR   	R10"             "\n\t"
"WDR   	"                "\n\t"
"LSR   	R7"              "\n\t"
"MUL   	R19, R6"         "\n\t"
"EOR   	R28, R16"        "\n\t"
"SUB   	R0, R16"         "\n\t"
"MUL   	R25, R30"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"LD    	R23, Y"          "\n\t"
"COM   	R10"             "\n\t"
"SBIC  	7, 4"            "\n\t"
"WDR   	"                "\n\t"
"SBRC  	R31, 7"          "\n\t"
"SWAP  	R29"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CP    	R10, R20"        "\n\t"
"BLD   	R23, 7"          "\n\t"
"LD    	R11, X"          "\n\t"
"ROR   	R17"             "\n\t"
"WDR   	"                "\n\t"
"CPI   	R21, 51"         "\n\t"
"LDD   	R5, Y+54"        "\n\t"
"BLD   	R29, 5"          "\n\t"
"BLD   	R14, 4"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"NEG   	R25"             "\n\t"
"SUB   	R26, R4"         "\n\t"
"LDI   	R31, 103"        "\n\t"
"OR    	R13, R23"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CBI   	29, 4"           "\n\t"
"WDR   	"                "\n\t"
"WDR   	"                "\n\t"
"SBIC  	30, 1"           "\n\t"
"SBC   	R0, R21"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LSR   	R21"             "\n\t"
"CALL  	Test_JMP"        "\n\t"
"MULS  	R17, R20"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"MOVW  	R18, R6"         "\n\t"
"LSR   	R13"             "\n\t"
"STS   	1208, R27"       "\n\t"
"ADD   	R12, R20"        "\n\t"
"AND   	R17, R8"         "\n\t"
"SBIC  	18, 4"           "\n\t"
"MULS  	R18, R27"        "\n\t"
"LPM   	"                "\n\t"
"ADC   	R22, R13"        "\n\t"
"ADD   	R16, R11"        "\n\t"
"FMUL  	R22, R21"        "\n\t"
"SUBI  	R27, 115"        "\n\t"
"ADC   	R5, R29"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CPSE  	R2, R17"         "\n\t"
"LPM   	R23, Z"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SUBI  	R27, 162"        "\n\t"
"FMULSU	R21, R23"        "\n\t"
"LD    	R7, -Z"          "\n\t"
"LDS   	R15, 601"        "\n\t"
"CPC   	R8, R16"         "\n\t"
"ADC   	R27, R14"        "\n\t"
"ST    	-Y, R25"         "\n\t"
"LDS   	R5, 1649"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"LSR   	R21"             "\n\t"
"MUL   	R20, R23"        "\n\t"
"CBI   	3, 2"            "\n\t"
"CPC   	R2, R0"          "\n\t"
"BCLR  	4"               "\n\t"
"STS   	681, R8"         "\n\t"
"SBIS  	18, 2"           "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"STD   	Y+12, R28"       "\n\t"
"SUB   	R5, R23"         "\n\t"
"CPC   	R7, R16"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BLD   	R26, 1"          "\n\t"
"SBI   	15, 4"           "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LDS   	R15, 1869"       "\n\t"
"LDS   	R9, 1376"        "\n\t"
"LDD   	R4, Y+25"        "\n\t"
"SUB   	R13, R24"        "\n\t"
"SBRC  	R20, 5"          "\n\t"
"LDD   	R24, Z+62"       "\n\t"
"LSR   	R25"             "\n\t"
"LDD   	R10, Z+17"       "\n\t"
"CPC   	R5, R24"         "\n\t"
"SBRC  	R13, 6"          "\n\t"
"SUBI  	R28, 55"         "\n\t"
"AND   	R14, R20"        "\n\t"
"BSET  	0"               "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SBIC  	16, 0"           "\n\t"
"CPC   	R6, R12"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SBRS  	R11, 0"          "\n\t"
"COM   	R14"             "\n\t"
"BST   	R21, 5"          "\n\t"
"ORI   	R16, 241"        "\n\t"
"LDD   	R3, Y+1"         "\n\t"
"SUBI  	R20, 54"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"OR    	R9, R13"         "\n\t"
"FMUL  	R21, R22"        "\n\t"
"LD    	R3, Y"           "\n\t"
"STS   	435, R30"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CPSE  	R23, R1"         "\n\t"
"MUL   	R14, R13"        "\n\t"
"WDR   	"                "\n\t"
"SUBI  	R28, 199"        "\n\t"
"WDR   	"                "\n\t"
"LPM   	R5, Z"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"FMUL  	R23, R18"        "\n\t"
"ADD   	R5, R24"         "\n\t"
"COM   	R8"              "\n\t"
"BST   	R26, 4"          "\n\t"
"COM   	R27"             "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ASR   	R26"             "\n\t"
"MUL   	R24, R14"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"BCLR  	4"               "\n\t"
"EOR   	R27, R26"        "\n\t"
"CPI   	R25, 162"        "\n\t"
"SBI   	23, 4"           "\n\t"
"SBIC  	13, 1"           "\n\t"
"LD    	R6, -Y"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CBI   	24, 3"           "\n\t"
"LDD   	R30, Z+53"       "\n\t"
"CP    	R21, R4"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SUB   	R25, R12"        "\n\t"
"CP    	R18, R29"        "\n\t"
"MULSU 	R19, R20"        "\n\t"
"LDS   	R7, 908"         "\n\t"
"WDR   	"                "\n\t"
"ADD   	R30, R28"        "\n\t"
"LD    	R9, Z"           "\n\t"
"SBI   	15, 7"           "\n\t"
"ADIW  	R24, 62"         "\n\t"
"SBIS  	17, 0"           "\n\t"
"BCLR  	2"               "\n\t"
"CP    	R11, R23"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"MOV   	R1, R31"         "\n\t"
"MOVW  	R4, R10"         "\n\t"
"AND   	R0, R22"         "\n\t"
"IN    	R15, 25"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BLD   	R21, 4"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ADC   	R14, R21"        "\n\t"
"SBRS  	R30, 4"          "\n\t"
"ASR   	R23"             "\n\t"
"SUBI  	R16, 221"        "\n\t"
"IN    	R10, 6"          "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"AND   	R11, R0"         "\n\t"
"SUBI  	R16, 254"        "\n\t"
"CPC   	R19, R9"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CP    	R1, R18"         "\n\t"
"SBRS  	R17, 5"          "\n\t"
"ADIW  	R24, 19"         "\n\t"
"CPI   	R27, 202"        "\n\t"
"SBCI  	R20, 226"        "\n\t"
"WDR   	"                "\n\t"
"MULSU 	R17, R16"        "\n\t"
"COM   	R28"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ASR   	R3"              "\n\t"
"MULSU 	R16, R19"        "\n\t"
"BCLR  	2"               "\n\t"
"ORI   	R31, 15"         "\n\t"
"CPC   	R17, R27"        "\n\t"
"SBRS  	R18, 5"          "\n\t"
"ANDI  	R17, 99"         "\n\t"
"BST   	R1, 4"           "\n\t"
"BCLR  	3"               "\n\t"
"ADC   	R25, R22"        "\n\t"
"CPSE  	R12, R11"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SER   	R25"             "\n\t"
"ROR   	R4"              "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"FMULSU	R20, R18"        "\n\t"
"CPI   	R28, 249"        "\n\t"
"ANDI  	R19, 202"        "\n\t"
"MULS  	R20, R19"        "\n\t"
"AND   	R29, R5"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"MULSU 	R18, R23"        "\n\t"
"MUL   	R1, R16"         "\n\t"
"SBRC  	R7, 1"           "\n\t"
"LSR   	R0"              "\n\t"
"LDD   	R4, Y+15"        "\n\t"
"COM   	R16"             "\n\t"
"LPM   	R12, Z+"         "\n\t"
"SBRC  	R11, 1"          "\n\t"
"ST    	Z, R2"           "\n\t"
"STS   	955, R8"         "\n\t"
"LDS   	R12, 1920"       "\n\t"
"WDR   	"                "\n\t"
"BSET  	3"               "\n\t"
"NEG   	R28"             "\n\t"
"NEG   	R7"              "\n\t"
"WDR   	"                "\n\t"
"FMUL  	R20, R23"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"MOV   	R30, R17"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LD    	R13, Y"          "\n\t"
"FMULS 	R17, R16"        "\n\t"
"SUBI  	R23, 76"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBC   	R20, R30"        "\n\t"
"WDR   	"                "\n\t"
"BCLR  	0"               "\n\t"
"BCLR  	7"               "\n\t"
"MULS  	R30, R26"        "\n\t"
"ADD   	R7, R19"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"BLD   	R30, 7"          "\n\t"
"CALL  	Test_JMP"        "\n\t"
"SBC   	R5, R8"          "\n\t"
"CBI   	15, 3"           "\n\t"
"WDR   	"                "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBIC  	3, 4"            "\n\t"
"STD   	Y+17, R28"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CBI   	24, 0"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CPSE  	R8, R13"         "\n\t"
"STS   	2294, R3"        "\n\t"
"LPM   	"                "\n\t"
"ADC   	R18, R1"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CPI   	R19, 182"        "\n\t"
"ADIW  	R26, 57"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"EOR   	R21, R1"         "\n\t"
"MUL   	R11, R5"         "\n\t"
"SBIC  	18, 3"           "\n\t"
"ADC   	R20, R23"        "\n\t"
"FMUL  	R22, R21"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LDI   	R17, 86"         "\n\t"
"OR    	R9, R18"         "\n\t"
"SER   	R19"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"MOVW  	R8, R20"         "\n\t"
"MULSU 	R17, R23"        "\n\t"
"SBC   	R1, R3"          "\n\t"
"ADC   	R16, R23"        "\n\t"
"BSET  	6"               "\n\t"
"WDR   	"                "\n\t"
"LDI   	R28, 14"         "\n\t"
"FMUL  	R22, R17"        "\n\t"
"IN    	R21, 57"         "\n\t"
"BST   	R4, 5"           "\n\t"
"MOVW  	R20, R30"        "\n\t"
"CPC   	R30, R21"        "\n\t"
"BSET  	5"               "\n\t"
"CPSE  	R14, R18"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"ASR   	R1"              "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SER   	R19"             "\n\t"
"COM   	R10"             "\n\t"
"SBIS  	21, 5"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"MOVW  	R20, R10"        "\n\t"
"ORI   	R16, 99"         "\n\t"
"ADIW  	R24, 47"         "\n\t"
"MOV   	R5, R4"          "\n\t"
"WDR   	"                "\n\t"
"SBC   	R26, R8"         "\n\t"
"SBC   	R30, R4"         "\n\t"
"SBIS  	26, 6"           "\n\t"
"SBCI  	R16, 33"         "\n\t"
"ADD   	R11, R26"        "\n\t"
"STD   	Z+14, R11"       "\n\t"
"WDR   	"                "\n\t"
"STD   	Y+60, R15"       "\n\t"
"SBI   	5, 5"            "\n\t"
"ASR   	R11"             "\n\t"
"MOVW  	R24, R14"        "\n\t"
"ADD   	R21, R26"        "\n\t"
"ST    	X, R8"           "\n\t"
"ADIW  	R28, 7"          "\n\t"
"NEG   	R16"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"OR    	R17, R16"        "\n\t"
"MUL   	R17, R2"         "\n\t"
"SBI   	18, 2"           "\n\t"
"WDR   	"                "\n\t"
"CPI   	R17, 95"         "\n\t"
"LDD   	R20, Z+29"       "\n\t"
"MULSU 	R18, R20"        "\n\t"
"ADD   	R2, R29"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"OR    	R19, R10"        "\n\t"
"NEG   	R31"             "\n\t"
"SBRC  	R19, 5"          "\n\t"
"MULSU 	R16, R17"        "\n\t"
"ANDI  	R21, 153"        "\n\t"
"IN    	R5, 49"          "\n\t"
"SBIC  	8, 1"            "\n\t"
"SBRC  	R14, 6"          "\n\t"
"BST   	R0, 4"           "\n\t"
"FMULS 	R18, R21"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBI   	12, 1"           "\n\t"
"FMULSU	R18, R21"        "\n\t"
"SER   	R21"             "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"MULS  	R30, R31"        "\n\t"
"STD   	Z+1, R14"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"LDD   	R23, Y+2"        "\n\t"
"OR    	R23, R29"        "\n\t"
"SBCI  	R27, 24"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SWAP  	R8"              "\n\t"
"MULS  	R19, R17"        "\n\t"
"LD    	R15, Y+"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"LDS   	R16, 2261"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBIC  	4, 1"            "\n\t"
"SUBI  	R16, 28"         "\n\t"
"LSR   	R20"             "\n\t"
"LPM   	R17, Z+"         "\n\t"
"SBIC  	15, 3"           "\n\t"
"COM   	R10"             "\n\t"
"LPM   	R14, Z+"         "\n\t"
"ROR   	R18"             "\n\t"
"SUBI  	R21, 165"        "\n\t"
"ROR   	R30"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"MULSU 	R17, R23"        "\n\t"
"WDR   	"                "\n\t"
"SBIC  	19, 4"           "\n\t"
"LSR   	R11"             "\n\t"
"IN    	R13, 53"         "\n\t"
"ADD   	R27, R15"        "\n\t"
"LDI   	R18, 237"        "\n\t"
"LSR   	R17"             "\n\t"
"AND   	R6, R16"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDI   	R29, 240"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"FMULS 	R23, R20"        "\n\t"
"SUB   	R29, R5"         "\n\t"
"BST   	R21, 3"          "\n\t"
"WDR   	"                "\n\t"
"ST    	Y, R14"          "\n\t"
"LSR   	R19"             "\n\t"
"SER   	R18"             "\n\t"
"SBC   	R15, R27"        "\n\t"
"FMUL  	R19, R21"        "\n\t"
"LDS   	R22, 1240"       "\n\t"
"MULS  	R16, R18"        "\n\t"
"ST    	Y+, R6"          "\n\t"
"LDD   	R2, Z+18"        "\n\t"
"ADD   	R14, R25"        "\n\t"
"ANDI  	R29, 151"        "\n\t"
"STD   	Z+61, R26"       "\n\t"
"SBC   	R19, R11"        "\n\t"
"CPC   	R25, R24"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SUB   	R4, R5"          "\n\t"
"SBI   	18, 3"           "\n\t"
"FMULS 	R21, R16"        "\n\t"
"SUB   	R2, R5"          "\n\t"
"LD    	R2, X"           "\n\t"
"LDI   	R25, 174"        "\n\t"
"COM   	R8"              "\n\t"
"IN    	R29, 27"         "\n\t"
"LPM   	R19, Z"          "\n\t"
"MULSU 	R21, R16"        "\n\t"
"LPM   	R15, Z+"         "\n\t"
"STD   	Z+29, R21"       "\n\t"
"MULSU 	R23, R16"        "\n\t"
"LDD   	R4, Z+29"        "\n\t"
"CBI   	3, 2"            "\n\t"
"ANDI  	R23, 228"        "\n\t"
"SBIS  	23, 6"           "\n\t"
"MOV   	R9, R10"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"NEG   	R19"             "\n\t"
"SBIS  	26, 6"           "\n\t"
"LPM   	R20, Z+"         "\n\t"
"LPM   	R0, Z"           "\n\t"
"CP    	R17, R5"         "\n\t"
"SBIS  	28, 7"           "\n\t"
"SER   	R26"             "\n\t"
"SER   	R31"             "\n\t"
"COM   	R18"             "\n\t"
"ST    	Z+, R19"         "\n\t"
"ADD   	R27, R7"         "\n\t"
"BLD   	R30, 6"          "\n\t"
"NEG   	R10"             "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"MOVW  	R6, R16"         "\n\t"
"STD   	Y+20, R30"       "\n\t"
"LD    	R13, Z"          "\n\t"
"CPSE  	R28, R10"        "\n\t"
"LPM   	R8, Z+"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SUB   	R4, R1"          "\n\t"
"STD   	Y+40, R7"        "\n\t"
"ADD   	R5, R18"         "\n\t"
"LPM   	R26, Z+"         "\n\t"
"ADC   	R11, R14"        "\n\t"
"SBI   	5, 2"            "\n\t"
"LDD   	R19, Z+50"       "\n\t"
"BST   	R23, 0"          "\n\t"
"SBCI  	R28, 199"        "\n\t"
"MULS  	R16, R30"        "\n\t"
"ORI   	R23, 64"         "\n\t"
"BLD   	R21, 5"          "\n\t"
"SER   	R25"             "\n\t"
"LDI   	R22, 221"        "\n\t"
"BLD   	R15, 0"          "\n\t"
"IN    	R22, 49"         "\n\t"
"SBCI  	R29, 11"         "\n\t"
"EOR   	R9, R15"         "\n\t"
"BLD   	R14, 7"          "\n\t"
"FMULSU	R21, R19"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"EOR   	R27, R14"        "\n\t"
"LDS   	R1, 590"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"SBIC  	13, 6"           "\n\t"
"SBRC  	R4, 4"           "\n\t"
"CP    	R29, R16"        "\n\t"
"MULSU 	R17, R16"        "\n\t"
"LDS   	R19, 1198"       "\n\t"
"SBRC  	R11, 5"          "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LDI   	R24, 98"         "\n\t"
"CBI   	19, 6"           "\n\t"
"LDD   	R8, Y+22"        "\n\t"
"FMULSU	R22, R23"        "\n\t"
"MOVW  	R6, R28"         "\n\t"
"LD    	R21, -Z"         "\n\t"
"OR    	R19, R24"        "\n\t"
"ST    	Y+, R11"         "\n\t"
"LSR   	R6"              "\n\t"
"LPM   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SER   	R25"             "\n\t"
"ADC   	R21, R15"        "\n\t"
"FMULS 	R19, R16"        "\n\t"
"ASR   	R23"             "\n\t"
"FMULSU	R19, R23"        "\n\t"
"SBIC  	20, 5"           "\n\t"
"WDR   	"                "\n\t"
"BSET  	3"               "\n\t"
"SBIS  	9, 6"            "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"ASR   	R9"              "\n\t"
"LDI   	R16, 63"         "\n\t"
"EOR   	R21, R3"         "\n\t"
"WDR   	"                "\n\t"
"MULSU 	R23, R21"        "\n\t"
"ADC   	R10, R16"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"FMULSU	R19, R19"        "\n\t"
"LPM   	R16, Z+"         "\n\t"
"LPM   	R18, Z"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CPI   	R28, 107"        "\n\t"
"OR    	R4, R10"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"STS   	1371, R10"       "\n\t"
"MOV   	R6, R22"         "\n\t"
"ST    	X, R17"          "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"LPM   	R22, Z+"         "\n\t"
"LPM   	"                "\n\t"
"SBCI  	R28, 45"         "\n\t"
"BST   	R4, 1"           "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"BSET  	5"               "\n\t"
"COM   	R29"             "\n\t"
"OR    	R17, R15"        "\n\t"
"BLD   	R15, 4"          "\n\t"
"LPM   	R1, Z+"          "\n\t"
"COM   	R7"              "\n\t"
"CPSE  	R0, R31"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ORI   	R17, 139"        "\n\t"
"SBRC  	R26, 3"          "\n\t"
"FMULSU	R20, R19"        "\n\t"
"BLD   	R19, 6"          "\n\t"
"LSR   	R24"             "\n\t"
"NEG   	R5"              "\n\t"
"STD   	Z+57, R25"       "\n\t"
"ADIW  	R24, 47"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"ANDI  	R27, 240"        "\n\t"
"ORI   	R31, 83"         "\n\t"
"CBI   	13, 1"           "\n\t"
"MOV   	R12, R6"         "\n\t"
"CPC   	R4, R4"          "\n\t"
"LPM   	"                "\n\t"
"LPM   	R25, Z+"         "\n\t"
"SBIS  	27, 6"           "\n\t"
"ADD   	R28, R17"        "\n\t"
"IN    	R21, 56"         "\n\t"
"LDS   	R1, 445"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"AND   	R8, R16"         "\n\t"
"BCLR  	1"               "\n\t"
"SBCI  	R25, 114"        "\n\t"
"ST    	X, R7"           "\n\t"
"FMUL  	R19, R20"        "\n\t"
"IN    	R19, 11"         "\n\t"
"ANDI  	R24, 40"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"MUL   	R27, R20"        "\n\t"
"CBI   	21, 4"           "\n\t"
"WDR   	"                "\n\t"
"FMULSU	R21, R21"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SUBI  	R21, 247"        "\n\t"
"MULSU 	R19, R18"        "\n\t"
"SWAP  	R16"             "\n\t"
"BST   	R4, 4"           "\n\t"
"ANDI  	R22, 142"        "\n\t"
"CPC   	R31, R14"        "\n\t"
"ADC   	R10, R9"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBRS  	R8, 2"           "\n\t"
"BLD   	R3, 4"           "\n\t"
"SBCI  	R23, 116"        "\n\t"
"FMUL  	R23, R23"        "\n\t"
"LPM   	"                "\n\t"
"EOR   	R29, R7"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CPI   	R22, 73"         "\n\t"
"STS   	1862, R4"        "\n\t"
"SBI   	2, 3"            "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"ST    	Z+, R0"          "\n\t"
"BST   	R18, 7"          "\n\t"
"ADIW  	R28, 26"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"MULSU 	R22, R21"        "\n\t"
"WDR   	"                "\n\t"
"SUB   	R20, R30"        "\n\t"
"WDR   	"                "\n\t"
"WDR   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDS   	R15, 1181"       "\n\t"
"SBRC  	R8, 0"           "\n\t"
"LSR   	R31"             "\n\t"
"LDD   	R31, Z+0"        "\n\t"
"MUL   	R22, R22"        "\n\t"
"MULS  	R22, R17"        "\n\t"
"BCLR  	7"               "\n\t"
"CPC   	R0, R19"         "\n\t"
"LD    	R7, Y"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBI   	27, 2"           "\n\t"
"FMULSU	R21, R18"        "\n\t"
"FMULSU	R18, R17"        "\n\t"
"SUB   	R6, R21"         "\n\t"
"STS   	787, R27"        "\n\t"
"COM   	R8"              "\n\t"
"COM   	R27"             "\n\t"
"SBIS  	1, 4"            "\n\t"
"COM   	R23"             "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BSET  	5"               "\n\t"
"COM   	R0"              "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SBRC  	R7, 3"           "\n\t"
"NEG   	R30"             "\n\t"
"CPSE  	R24, R25"        "\n\t"
"SBRC  	R18, 5"          "\n\t"
"WDR   	"                "\n\t"
"ANDI  	R25, 130"        "\n\t"
"ASR   	R5"              "\n\t"
"FMULS 	R23, R21"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SBRC  	R23, 4"          "\n\t"
"STS   	750, R14"        "\n\t"
"COM   	R1"              "\n\t"
"FMULSU	R19, R17"        "\n\t"
"LD    	R3, Z+"          "\n\t"
"ORI   	R18, 107"        "\n\t"
"IN    	R28, 42"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDI   	R25, 16"         "\n\t"
"CPC   	R19, R4"         "\n\t"
"FMULS 	R18, R17"        "\n\t"
"LDD   	R26, Y+16"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SWAP  	R1"              "\n\t"
"LDS   	R19, 1685"       "\n\t"
"SBRC  	R17, 7"          "\n\t"
"CALL  	Test_CALL"       "\n\t"
"STS   	1019, R8"        "\n\t"
"LDS   	R27, 1097"       "\n\t"
"WDR   	"                "\n\t"
"BLD   	R17, 6"          "\n\t"
"FMUL  	R21, R21"        "\n\t"
"ORI   	R22, 147"        "\n\t"
"ADD   	R0, R19"         "\n\t"
"LPM   	R14, Z"          "\n\t"
"ROR   	R6"              "\n\t"
"STD   	Y+56, R30"       "\n\t"
"CPSE  	R8, R31"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"MUL   	R27, R22"        "\n\t"
"SBRS  	R27, 7"          "\n\t"
"LDS   	R26, 1947"       "\n\t"
"ANDI  	R23, 116"        "\n\t"
"SUB   	R25, R16"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LSR   	R22"             "\n\t"
"FMULSU	R22, R21"        "\n\t"
"LSR   	R10"             "\n\t"
"COM   	R31"             "\n\t"
"SBIS  	14, 1"           "\n\t"
"SWAP  	R22"             "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBI   	27, 7"           "\n\t"
"SBCI  	R20, 48"         "\n\t"
"CPI   	R20, 236"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBIC  	1, 7"            "\n\t"
"ORI   	R27, 125"        "\n\t"
"ADC   	R1, R24"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBCI  	R30, 192"        "\n\t"
"OR    	R5, R31"         "\n\t"
"ANDI  	R17, 237"        "\n\t"
"SBIC  	29, 0"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SWAP  	R2"              "\n\t"
"COM   	R1"              "\n\t"
"MULS  	R21, R22"        "\n\t"
"MOV   	R12, R13"        "\n\t"
"ORI   	R24, 229"        "\n\t"
"EOR   	R20, R26"        "\n\t"
"BSET  	3"               "\n\t"
"SBIC  	24, 3"           "\n\t"
"MUL   	R6, R31"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"FMULSU	R21, R18"        "\n\t"
"WDR   	"                "\n\t"
"IN    	R11, 55"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CP    	R3, R28"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"MULS  	R16, R31"        "\n\t"
"SER   	R19"             "\n\t"
"EOR   	R1, R24"         "\n\t"
"FMULS 	R16, R17"        "\n\t"
"STD   	Z+29, R6"        "\n\t"
"STD   	Y+19, R22"       "\n\t"
"ADIW  	R24, 32"         "\n\t"
"ADD   	R28, R3"         "\n\t"
"SBI   	19, 7"           "\n\t"
"EOR   	R8, R17"         "\n\t"
"STD   	Y+61, R8"        "\n\t"
"ORI   	R18, 77"         "\n\t"
"WDR   	"                "\n\t"
"ADC   	R13, R8"         "\n\t"
"SUB   	R13, R22"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SBCI  	R26, 57"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CP    	R1, R2"          "\n\t"
"SUBI  	R16, 5"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ORI   	R31, 160"        "\n\t"
"EOR   	R2, R25"         "\n\t"
"COM   	R17"             "\n\t"
"SBC   	R17, R31"        "\n\t"
"STD   	Y+17, R5"        "\n\t"
"BLD   	R6, 2"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SWAP  	R23"             "\n\t"
"CP    	R5, R11"         "\n\t"
"WDR   	"                "\n\t"
"LSR   	R23"             "\n\t"
"LDD   	R16, Y+29"       "\n\t"
"SUBI  	R22, 15"         "\n\t"
"FMUL  	R16, R21"        "\n\t"
"BCLR  	0"               "\n\t"
"FMULSU	R17, R18"        "\n\t"
"LDD   	R21, Y+36"       "\n\t"
"LPM   	"                "\n\t"
"WDR   	"                "\n\t"
"IN    	R9, 29"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"FMUL  	R17, R18"        "\n\t"
"MOVW  	R20, R10"        "\n\t"
"COM   	R20"             "\n\t"
"LDD   	R18, Z+5"        "\n\t"
"ADD   	R5, R31"         "\n\t"
"SBC   	R1, R21"         "\n\t"
"LD    	R14, Z+"         "\n\t"
"NEG   	R10"             "\n\t"
"WDR   	"                "\n\t"
"WDR   	"                "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBC   	R25, R14"        "\n\t"
"SWAP  	R24"             "\n\t"
"SWAP  	R9"              "\n\t"
"CALL  	Test_JMP"        "\n\t"
"SER   	R16"             "\n\t"
"STS   	286, R0"         "\n\t"
"FMULS 	R18, R18"        "\n\t"
"MULS  	R23, R23"        "\n\t"
"LSR   	R11"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"OR    	R2, R17"         "\n\t"
"ADD   	R3, R6"          "\n\t"
"ADC   	R7, R23"         "\n\t"
"COM   	R17"             "\n\t"
"SBI   	1, 7"            "\n\t"
"MUL   	R8, R14"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CPSE  	R12, R6"         "\n\t"
"NEG   	R19"             "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"OR    	R21, R24"        "\n\t"
"CPI   	R20, 182"        "\n\t"
"SUBI  	R25, 113"        "\n\t"
"ASR   	R21"             "\n\t"
"LPM   	"                "\n\t"
"NEG   	R16"             "\n\t"
"CPC   	R23, R2"         "\n\t"
"SUBI  	R31, 223"        "\n\t"
"NEG   	R7"              "\n\t"
"EOR   	R14, R3"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CP    	R11, R27"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"ST    	-Z, R0"          "\n\t"
"IN    	R7, 22"          "\n\t"
"SUB   	R21, R29"        "\n\t"
"LPM   	"                "\n\t"
"CALL  	Test_CALL"       "\n\t"
"MUL   	R3, R11"         "\n\t"
"COM   	R13"             "\n\t"
"SBC   	R23, R8"         "\n\t"
"OR    	R14, R2"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"FMULSU	R18, R17"        "\n\t"
"ROR   	R8"              "\n\t"
"SBCI  	R24, 93"         "\n\t"
"SWAP  	R6"              "\n\t"
"MULSU 	R21, R21"        "\n\t"
"CPC   	R23, R24"        "\n\t"
"SBI   	17, 1"           "\n\t"
"EOR   	R13, R7"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"NEG   	R14"             "\n\t"
"FMULSU	R17, R19"        "\n\t"
"IN    	R13, 20"         "\n\t"
"ADIW  	R26, 48"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LDD   	R16, Z+53"       "\n\t"
"CP    	R30, R0"         "\n\t"
"CPSE  	R20, R17"        "\n\t"
"COM   	R21"             "\n\t"
"ROR   	R8"              "\n\t"
"CPI   	R20, 38"         "\n\t"
"BST   	R29, 2"          "\n\t"
"ORI   	R29, 63"         "\n\t"
"CP    	R24, R15"        "\n\t"
"LDD   	R4, Y+52"        "\n\t"
"WDR   	"                "\n\t"
"SWAP  	R24"             "\n\t"
"CPC   	R11, R0"         "\n\t"
"BLD   	R10, 6"          "\n\t"
"SBIS  	2, 1"            "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDI   	R20, 196"        "\n\t"
"STD   	Y+53, R12"       "\n\t"
"WDR   	"                "\n\t"
"MUL   	R7, R13"         "\n\t"
"BSET  	0"               "\n\t"
"FMUL  	R19, R21"        "\n\t"
"MULS  	R23, R23"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"STD   	Y+47, R17"       "\n\t"
"WDR   	"                "\n\t"
"FMULS 	R16, R20"        "\n\t"
"FMULS 	R20, R20"        "\n\t"
"SBRC  	R8, 6"           "\n\t"
"FMULS 	R19, R21"        "\n\t"
"OR    	R26, R13"        "\n\t"
"LDD   	R26, Y+25"       "\n\t"
"ST    	-Y, R2"          "\n\t"
"MULSU 	R19, R16"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"STD   	Y+12, R8"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LPM   	R17, Z+"         "\n\t"
"BCLR  	3"               "\n\t"
"LDS   	R5, 1892"        "\n\t"
"ADIW  	R24, 60"         "\n\t"
"BLD   	R2, 4"           "\n\t"
"CBI   	24, 1"           "\n\t"
"BLD   	R18, 2"          "\n\t"
"SWAP  	R26"             "\n\t"
"CP    	R9, R18"         "\n\t"
"CBI   	14, 7"           "\n\t"
"ASR   	R27"             "\n\t"
"ADIW  	R24, 44"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"LDS   	R14, 513"        "\n\t"
"CPI   	R20, 113"        "\n\t"
"ASR   	R11"             "\n\t"
"SUB   	R12, R25"        "\n\t"
"MULS  	R31, R22"        "\n\t"
"STS   	2202, R26"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBI   	4, 6"            "\n\t"
"ROR   	R13"             "\n\t"
"LPM   	R29, Z+"         "\n\t"
"MULS  	R19, R29"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SUB   	R11, R8"         "\n\t"
"FMUL  	R18, R23"        "\n\t"
"LPM   	R1, Z"           "\n\t"
"CPSE  	R23, R18"        "\n\t"
"FMULS 	R18, R18"        "\n\t"
"SBRS  	R3, 3"           "\n\t"
"LD    	R12, -X"         "\n\t"
"SWAP  	R1"              "\n\t"
"SER   	R31"             "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"SBIS  	12, 2"           "\n\t"
"STD   	Z+33, R3"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"EOR   	R6, R12"         "\n\t"
"MUL   	R2, R21"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LSR   	R28"             "\n\t"
"ADD   	R9, R31"         "\n\t"
"ROR   	R6"              "\n\t"
"LD    	R0, Y+"          "\n\t"
"LDI   	R22, 116"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"IN    	R13, 21"         "\n\t"
"STS   	2148, R11"       "\n\t"
"CPC   	R18, R22"        "\n\t"
"EOR   	R23, R17"        "\n\t"
"SBI   	9, 4"            "\n\t"
"AND   	R28, R4"         "\n\t"
"LD    	R4, -X"          "\n\t"
"MOVW  	R20, R28"        "\n\t"
"STS   	1304, R14"       "\n\t"
"ADC   	R24, R4"         "\n\t"
"STD   	Y+45, R8"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"WDR   	"                "\n\t"
"BCLR  	0"               "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BCLR  	4"               "\n\t"
"CBI   	31, 2"           "\n\t"
"WDR   	"                "\n\t"
"BCLR  	2"               "\n\t"
"CP    	R25, R24"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CPSE  	R7, R17"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SWAP  	R20"             "\n\t"
"LDS   	R9, 780"         "\n\t"
"IN    	R21, 52"         "\n\t"
"SUBI  	R23, 157"        "\n\t"
"BST   	R15, 4"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"ASR   	R11"             "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"EOR   	R14, R30"        "\n\t"
"CBI   	24, 6"           "\n\t"
"BST   	R25, 5"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDS   	R19, 1520"       "\n\t"
"BST   	R9, 1"           "\n\t"
"WDR   	"                "\n\t"
"WDR   	"                "\n\t"
"SBIC  	9, 6"            "\n\t"
"NEG   	R9"              "\n\t"
"SER   	R16"             "\n\t"
"WDR   	"                "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SWAP  	R22"             "\n\t"
"MUL   	R25, R10"        "\n\t"
"SBRC  	R31, 3"          "\n\t"
"CALL  	Test_CALL"       "\n\t"
"STD   	Y+20, R23"       "\n\t"
"ADD   	R25, R22"        "\n\t"
"CP    	R31, R1"         "\n\t"
"WDR   	"                "\n\t"
"CALL  	Test_CALL"       "\n\t"
"BLD   	R10, 3"          "\n\t"
"WDR   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CP    	R30, R27"        "\n\t"
"ADC   	R5, R3"          "\n\t"
"CPI   	R19, 223"        "\n\t"
"IN    	R24, 60"         "\n\t"
"EOR   	R19, R9"         "\n\t"
"CBI   	9, 4"            "\n\t"
"SBIC  	11, 2"           "\n\t"
"WDR   	"                "\n\t"
"WDR   	"                "\n\t"
"BSET  	3"               "\n\t"
"IN    	R7, 52"          "\n\t"
"ROR   	R11"             "\n\t"
"CP    	R27, R18"        "\n\t"
"ST    	X+, R22"         "\n\t"
"LSR   	R31"             "\n\t"
"CBI   	9, 2"            "\n\t"
"STS   	1568, R31"       "\n\t"
"CP    	R0, R7"          "\n\t"
"SBI   	20, 6"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ORI   	R16, 109"        "\n\t"
"SBRC  	R3, 7"           "\n\t"
"LDD   	R9, Z+10"        "\n\t"
"LDD   	R15, Z+0"        "\n\t"
"STD   	Z+47, R26"       "\n\t"
"LDI   	R25, 42"         "\n\t"
"CBI   	18, 4"           "\n\t"
"CPC   	R2, R0"          "\n\t"
"LSR   	R10"             "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CP    	R14, R4"         "\n\t"
"BST   	R5, 3"           "\n\t"
"ORI   	R29, 225"        "\n\t"
"WDR   	"                "\n\t"
"LDD   	R7, Y+43"        "\n\t"
"SBIS  	16, 1"           "\n\t"
"CALL  	Test_JMP"        "\n\t"
"LDI   	R23, 242"        "\n\t"
"NEG   	R8"              "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CP    	R21, R31"        "\n\t"
"MUL   	R8, R1"          "\n\t"
"SBIS  	10, 2"           "\n\t"
"CPI   	R30, 81"         "\n\t"
"SUBI  	R29, 61"         "\n\t"
"ADC   	R11, R7"         "\n\t"
"SBC   	R10, R9"         "\n\t"
"OR    	R6, R9"          "\n\t"
"SBCI  	R30, 250"        "\n\t"
"CPSE  	R19, R29"        "\n\t"
"BST   	R6, 3"           "\n\t"
"LDI   	R19, 64"         "\n\t"
"LDD   	R10, Y+58"       "\n\t"
"BCLR  	6"               "\n\t"
"OR    	R24, R13"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"WDR   	"                "\n\t"
"WDR   	"                "\n\t"
"SUB   	R1, R27"         "\n\t"
"MULS  	R19, R22"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ROR   	R15"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CPC   	R28, R19"        "\n\t"
"STS   	798, R21"        "\n\t"
"BST   	R27, 4"          "\n\t"
"CPSE  	R2, R10"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ORI   	R20, 50"         "\n\t"
"SER   	R29"             "\n\t"
"ADD   	R15, R21"        "\n\t"
"ORI   	R18, 134"        "\n\t"
"SER   	R21"             "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"STD   	Y+18, R16"       "\n\t"
"ST    	Y+, R12"         "\n\t"
"LPM   	"                "\n\t"
"BSET  	2"               "\n\t"
"FMUL  	R19, R23"        "\n\t"
"LSR   	R28"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"WDR   	"                "\n\t"
"STD   	Y+35, R21"       "\n\t"
"LDI   	R16, 114"        "\n\t"
"LSR   	R20"             "\n\t"
"ST    	X+, R4"          "\n\t"
"SER   	R31"             "\n\t"
"ADIW  	R30, 20"         "\n\t"
"ANDI  	R17, 228"        "\n\t"
"CP    	R15, R4"         "\n\t"
"LPM   	"                "\n\t"
"CBI   	30, 1"           "\n\t"
"ANDI  	R19, 205"        "\n\t"
"ST    	X, R25"          "\n\t"
"CBI   	3, 4"            "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"BST   	R4, 7"           "\n\t"
"MOVW  	R0, R22"         "\n\t"
"ORI   	R31, 53"         "\n\t"
"ADIW  	R26, 57"         "\n\t"
"BSET  	2"               "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CPC   	R17, R22"        "\n\t"
"LPM   	"                "\n\t"
"CPI   	R17, 5"          "\n\t"
"ANDI  	R17, 19"         "\n\t"
"FMUL  	R22, R17"        "\n\t"
"BLD   	R4, 1"           "\n\t"
"WDR   	"                "\n\t"
"SWAP  	R16"             "\n\t"
"SBI   	10, 3"           "\n\t"
"MOV   	R14, R13"        "\n\t"
"LPM   	R18, Z"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"MOVW  	R20, R28"        "\n\t"
"MUL   	R1, R31"         "\n\t"
"SUBI  	R20, 215"        "\n\t"
"CPC   	R5, R7"          "\n\t"
"ASR   	R15"             "\n\t"
"AND   	R14, R20"        "\n\t"
"LSR   	R18"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CPI   	R24, 127"        "\n\t"
"ADC   	R24, R21"        "\n\t"
"BSET  	0"               "\n\t"
"ADIW  	R28, 7"          "\n\t"
"CPC   	R30, R5"         "\n\t"
"CBI   	31, 0"           "\n\t"
"LPM   	R18, Z"          "\n\t"
"COM   	R15"             "\n\t"
"CBI   	2, 5"            "\n\t"
"SBRS  	R17, 4"          "\n\t"
"SBC   	R17, R9"         "\n\t"
"FMULS 	R18, R22"        "\n\t"
"OR    	R15, R8"         "\n\t"
"SBCI  	R17, 141"        "\n\t"
"FMUL  	R20, R16"        "\n\t"
"SUB   	R13, R30"        "\n\t"
"BST   	R21, 2"          "\n\t"
"SBIS  	0, 6"            "\n\t"
"LDS   	R1, 437"         "\n\t"
"LSR   	R12"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"STD   	Y+38, R10"       "\n\t"
"NEG   	R9"              "\n\t"
"STS   	961, R5"         "\n\t"
"BCLR  	4"               "\n\t"
"ORI   	R28, 44"         "\n\t"
"MUL   	R15, R2"         "\n\t"
"ADD   	R8, R23"         "\n\t"
"SWAP  	R4"              "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CPSE  	R28, R27"        "\n\t"
"CBI   	21, 0"           "\n\t"
"LDS   	R5, 595"         "\n\t"
"CPI   	R18, 9"          "\n\t"
"SUB   	R11, R4"         "\n\t"
"ROR   	R17"             "\n\t"
"ADIW  	R26, 48"         "\n\t"
"LSR   	R9"              "\n\t"
"SBRC  	R17, 6"          "\n\t"
"BCLR  	0"               "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ST    	Z+, R14"         "\n\t"
"ADIW  	R24, 27"         "\n\t"
"LDS   	R0, 1889"        "\n\t"
"FMUL  	R23, R16"        "\n\t"
"FMULS 	R16, R23"        "\n\t"
"SER   	R26"             "\n\t"
"ST    	-Y, R15"         "\n\t"
"IN    	R21, 12"         "\n\t"
"MOVW  	R2, R8"          "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ADC   	R23, R11"        "\n\t"
"NEG   	R7"              "\n\t"
"AND   	R9, R19"         "\n\t"
"LPM   	"                "\n\t"
"SUBI  	R19, 183"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"BCLR  	3"               "\n\t"
"FMULSU	R20, R21"        "\n\t"
"STS   	2287, R16"       "\n\t"
"MUL   	R21, R6"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CPI   	R29, 49"         "\n\t"
"SBCI  	R24, 110"        "\n\t"
"WDR   	"                "\n\t"
"LD    	R24, Y"          "\n\t"
"ORI   	R31, 198"        "\n\t"
"MOVW  	R8, R12"         "\n\t"
"CBI   	20, 7"           "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SUB   	R8, R15"         "\n\t"
"SBIS  	27, 6"           "\n\t"
"SBI   	15, 6"           "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"ASR   	R13"             "\n\t"
"WDR   	"                "\n\t"
"SBC   	R17, R6"         "\n\t"
"ORI   	R17, 212"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ADD   	R4, R17"         "\n\t"
"SBCI  	R21, 68"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"MULS  	R18, R28"        "\n\t"
"SWAP  	R21"             "\n\t"
"CBI   	19, 7"           "\n\t"
"IN    	R17, 19"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBI   	20, 0"           "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CPSE  	R0, R7"          "\n\t"
"SBC   	R8, R9"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CP    	R18, R6"         "\n\t"
"COM   	R0"              "\n\t"
"ASR   	R16"             "\n\t"
"ANDI  	R25, 189"        "\n\t"
"AND   	R22, R23"        "\n\t"
"ANDI  	R20, 171"        "\n\t"
"LDI   	R27, 77"         "\n\t"
"SUBI  	R16, 38"         "\n\t"
"FMULSU	R17, R18"        "\n\t"
"SWAP  	R12"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LPM   	R19, Z"          "\n\t"
"CPC   	R21, R5"         "\n\t"
"BLD   	R25, 1"          "\n\t"
"FMUL  	R21, R21"        "\n\t"
"LDD   	R27, Y+29"       "\n\t"
"ORI   	R27, 226"        "\n\t"
"CBI   	8, 2"            "\n\t"
"LSR   	R6"              "\n\t"
"LPM   	R11, Z+"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"FMULSU	R23, R17"        "\n\t"
"LPM   	"                "\n\t"
"BST   	R14, 2"          "\n\t"
"SWAP  	R2"              "\n\t"
"CPSE  	R3, R30"         "\n\t"
"ST    	-X, R25"         "\n\t"
"CPI   	R27, 19"         "\n\t"
"FMULS 	R21, R17"        "\n\t"
"LDI   	R19, 94"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ORI   	R27, 223"        "\n\t"
"BLD   	R12, 2"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CPI   	R22, 149"        "\n\t"
"LDS   	R22, 2276"       "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ANDI  	R27, 223"        "\n\t"
"WDR   	"                "\n\t"
"SER   	R25"             "\n\t"
"SWAP  	R30"             "\n\t"
"SBCI  	R22, 29"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"BLD   	R14, 6"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"FMULS 	R23, R21"        "\n\t"
"FMUL  	R23, R19"        "\n\t"
"MULS  	R20, R25"        "\n\t"
"STS   	1464, R22"       "\n\t"
"WDR   	"                "\n\t"
"COM   	R14"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"AND   	R23, R25"        "\n\t"
"COM   	R30"             "\n\t"
"SUB   	R9, R31"         "\n\t"
"ORI   	R20, 90"         "\n\t"
"ORI   	R23, 44"         "\n\t"
"MULSU 	R22, R17"        "\n\t"
"EOR   	R27, R4"         "\n\t"
"BST   	R12, 3"          "\n\t"
"BST   	R25, 4"          "\n\t"
"ORI   	R30, 208"        "\n\t"
"EOR   	R8, R4"          "\n\t"
"STD   	Z+8, R5"         "\n\t"
"AND   	R31, R28"        "\n\t"
"ADC   	R0, R6"          "\n\t"
"BLD   	R11, 5"          "\n\t"
"BST   	R29, 1"          "\n\t"
"AND   	R26, R1"         "\n\t"
"FMULS 	R19, R21"        "\n\t"
"LDI   	R16, 6"          "\n\t"
"ROR   	R13"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDD   	R21, Y+12"       "\n\t"
"WDR   	"                "\n\t"
"CBI   	16, 5"           "\n\t"
"CALL  	Test_CALL"       "\n\t"
"FMULS 	R22, R22"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ST    	-Z, R6"          "\n\t"
"STS   	344, R17"        "\n\t"
"AND   	R26, R11"        "\n\t"
"ROR   	R20"             "\n\t"
"STD   	Z+29, R29"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LD    	R7, -X"          "\n\t"
"CP    	R26, R10"        "\n\t"
"LDI   	R30, 49"         "\n\t"
"SBI   	26, 4"           "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CPSE  	R7, R22"         "\n\t"
"LDS   	R29, 841"        "\n\t"
"FMULS 	R21, R21"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ROR   	R20"             "\n\t"
"ADC   	R5, R26"         "\n\t"
"MULS  	R27, R21"        "\n\t"
"ORI   	R22, 224"        "\n\t"
"IN    	R5, 62"          "\n\t"
"BLD   	R9, 2"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"LPM   	R9, Z"           "\n\t"
"SBIS  	22, 2"           "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ADC   	R30, R3"         "\n\t"
"ASR   	R29"             "\n\t"
"ANDI  	R21, 243"        "\n\t"
"SER   	R23"             "\n\t"
"MOVW  	R14, R18"        "\n\t"
"ORI   	R22, 122"        "\n\t"
"SBI   	29, 5"           "\n\t"
"LSR   	R15"             "\n\t"
"SBI   	11, 1"           "\n\t"
"WDR   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SER   	R17"             "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"NEG   	R28"             "\n\t"
"LDI   	R29, 120"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"BSET  	4"               "\n\t"
"IN    	R26, 29"         "\n\t"
"MOV   	R29, R16"        "\n\t"
"MUL   	R23, R4"         "\n\t"
"CPSE  	R5, R4"          "\n\t"
"LDS   	R2, 707"         "\n\t"
"CP    	R4, R21"         "\n\t"
"SER   	R19"             "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBIC  	23, 5"           "\n\t"
"MOVW  	R28, R12"        "\n\t"
"CP    	R24, R22"        "\n\t"
"ADIW  	R26, 53"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"LDI   	R16, 149"        "\n\t"
"SUBI  	R30, 26"         "\n\t"
"SBI   	27, 0"           "\n\t"
"SBI   	25, 4"           "\n\t"
"ANDI  	R22, 114"        "\n\t"
"SER   	R31"             "\n\t"
"WDR   	"                "\n\t"
"ADC   	R4, R28"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBCI  	R20, 75"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"EOR   	R11, R24"        "\n\t"
"SWAP  	R22"             "\n\t"
"MOVW  	R2, R26"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"STD   	Y+57, R31"       "\n\t"
"ASR   	R12"             "\n\t"
"LPM   	"                "\n\t"
"IN    	R5, 12"          "\n\t"
"ST    	-Z, R7"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BST   	R24, 6"          "\n\t"
"FMUL  	R20, R17"        "\n\t"
"SBRC  	R0, 7"           "\n\t"
"ASR   	R7"              "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CPC   	R31, R29"        "\n\t"
"SUB   	R5, R14"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"MULS  	R29, R30"        "\n\t"
"MULS  	R18, R30"        "\n\t"
"ST    	-Z, R13"         "\n\t"
"SBI   	14, 0"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LD    	R24, Y"          "\n\t"
"LPM   	"                "\n\t"
"WDR   	"                "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ROR   	R17"             "\n\t"
"COM   	R31"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ADD   	R8, R16"         "\n\t"
"MOV   	R9, R26"         "\n\t"
"BST   	R25, 6"          "\n\t"
"CPSE  	R7, R29"         "\n\t"
"CPI   	R19, 37"         "\n\t"
"SER   	R19"             "\n\t"
"LSR   	R10"             "\n\t"
"WDR   	"                "\n\t"
"ST    	X+, R2"          "\n\t"
"WDR   	"                "\n\t"
"CPC   	R30, R14"        "\n\t"
"LDD   	R27, Z+23"       "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"COM   	R29"             "\n\t"
"SBIS  	17, 1"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SWAP  	R31"             "\n\t"
"WDR   	"                "\n\t"
"BSET  	5"               "\n\t"
"EOR   	R9, R17"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"OR    	R25, R27"        "\n\t"
"BSET  	5"               "\n\t"
"BST   	R29, 1"          "\n\t"
"FMULS 	R21, R21"        "\n\t"
"SBIC  	15, 5"           "\n\t"
"BLD   	R10, 3"          "\n\t"
"SBIS  	27, 6"           "\n\t"
"LD    	R7, X"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"AND   	R23, R7"         "\n\t"
"SBRC  	R8, 0"           "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"STS   	1121, R2"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SBI   	10, 0"           "\n\t"
"CP    	R17, R15"        "\n\t"
"WDR   	"                "\n\t"
"ROR   	R10"             "\n\t"
"EOR   	R15, R6"         "\n\t"
"LD    	R6, X"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CBI   	20, 4"           "\n\t"
"EOR   	R24, R2"         "\n\t"
"MOV   	R19, R16"        "\n\t"
"BSET  	1"               "\n\t"
"ADC   	R31, R26"        "\n\t"
"BCLR  	0"               "\n\t"
"ROR   	R30"             "\n\t"
"SBRS  	R19, 4"          "\n\t"
"SBRS  	R2, 6"           "\n\t"
"NEG   	R27"             "\n\t"
"SBC   	R17, R28"        "\n\t"
"IN    	R6, 32"          "\n\t"
"SBRS  	R3, 3"           "\n\t"
"CP    	R25, R22"        "\n\t"
"SBIC  	17, 1"           "\n\t"
"LD    	R13, X"          "\n\t"
"LSR   	R5"              "\n\t"
"CPC   	R0, R17"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"MULS  	R30, R29"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBI   	8, 4"            "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_JMP"        "\n\t"
"SER   	R23"             "\n\t"
"MOV   	R9, R20"         "\n\t"
"LDI   	R21, 149"        "\n\t"
"STS   	1223, R17"       "\n\t"
"AND   	R5, R2"          "\n\t"
"SBRC  	R4, 0"           "\n\t"
"ADC   	R16, R4"         "\n\t"
"SBRC  	R8, 1"           "\n\t"
"BLD   	R14, 3"          "\n\t"
"BST   	R30, 5"          "\n\t"
"SER   	R21"             "\n\t"
"CPC   	R11, R3"         "\n\t"
"SBRS  	R2, 5"           "\n\t"
"ADIW  	R24, 28"         "\n\t"
"MUL   	R31, R21"        "\n\t"
"ORI   	R17, 46"         "\n\t"
"IN    	R11, 51"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BST   	R23, 4"          "\n\t"
"LSR   	R27"             "\n\t"
"LPM   	R10, Z+"         "\n\t"
"LDD   	R1, Z+52"        "\n\t"
"AND   	R23, R24"        "\n\t"
"BSET  	0"               "\n\t"
"SWAP  	R4"              "\n\t"
"ADC   	R28, R25"        "\n\t"
"FMUL  	R18, R16"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SWAP  	R13"             "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LDS   	R22, 1921"       "\n\t"
"BLD   	R31, 3"          "\n\t"
"EOR   	R1, R7"          "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SBIC  	3, 6"            "\n\t"
"WDR   	"                "\n\t"
"SBC   	R28, R28"        "\n\t"
"SBIC  	2, 4"            "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"COM   	R14"             "\n\t"
"STD   	Z+4, R29"        "\n\t"
"MOV   	R5, R14"         "\n\t"
"SBI   	19, 1"           "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"WDR   	"                "\n\t"
"CPC   	R29, R9"         "\n\t"
"CPSE  	R27, R22"        "\n\t"
"CP    	R2, R24"         "\n\t"
"LDD   	R21, Y+38"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"WDR   	"                "\n\t"
"LPM   	R16, Z"          "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SUBI  	R27, 11"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"SBC   	R14, R22"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ADD   	R12, R4"         "\n\t"
"CP    	R23, R17"        "\n\t"
"WDR   	"                "\n\t"
"LDD   	R8, Y+58"        "\n\t"
"BCLR  	5"               "\n\t"
"WDR   	"                "\n\t"
"MOV   	R23, R22"        "\n\t"
"FMULS 	R20, R23"        "\n\t"
"MULS  	R23, R21"        "\n\t"
"LSR   	R29"             "\n\t"
"WDR   	"                "\n\t"
"FMULS 	R21, R18"        "\n\t"
"FMUL  	R19, R16"        "\n\t"
"LPM   	R17, Z+"         "\n\t"
"CPC   	R7, R17"         "\n\t"
"FMULSU	R21, R21"        "\n\t"
"ANDI  	R26, 223"        "\n\t"
"ADIW  	R26, 59"         "\n\t"
"LD    	R15, X+"         "\n\t"
"SBRS  	R28, 5"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"WDR   	"                "\n\t"
"ORI   	R28, 28"         "\n\t"
"LDS   	R19, 651"        "\n\t"
"ANDI  	R27, 129"        "\n\t"
"CPSE  	R15, R13"        "\n\t"
"BCLR  	2"               "\n\t"
"STS   	645, R14"        "\n\t"
"LDI   	R28, 19"         "\n\t"
"WDR   	"                "\n\t"
"ADD   	R16, R7"         "\n\t"
"SBRS  	R22, 2"          "\n\t"
"MUL   	R0, R31"         "\n\t"
"LPM   	R13, Z+"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"BCLR  	2"               "\n\t"
"CPI   	R31, 159"        "\n\t"
"MOV   	R16, R11"        "\n\t"
"LDI   	R20, 206"        "\n\t"
"ADC   	R24, R24"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBC   	R25, R5"         "\n\t"
"SBCI  	R20, 25"         "\n\t"
"WDR   	"                "\n\t"
"SBI   	13, 7"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"STS   	1425, R8"        "\n\t"
"CPI   	R19, 70"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"BLD   	R10, 3"          "\n\t"
"FMULS 	R19, R21"        "\n\t"
"BLD   	R11, 0"          "\n\t"
"LDI   	R23, 155"        "\n\t"
"BCLR  	2"               "\n\t"
"FMUL  	R19, R23"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ADC   	R7, R10"         "\n\t"
"LD    	R21, -Y"         "\n\t"
"FMULSU	R16, R16"        "\n\t"
"COM   	R11"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SUB   	R4, R0"          "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CPC   	R6, R3"          "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"ST    	-X, R5"          "\n\t"
"SBRC  	R2, 2"           "\n\t"
"CALL  	Test_JMP"        "\n\t"
"STD   	Y+11, R21"       "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"OR    	R5, R10"         "\n\t"
"ANDI  	R19, 199"        "\n\t"
"ST    	Z+, R25"         "\n\t"
"OR    	R14, R7"         "\n\t"
"SBC   	R29, R23"        "\n\t"
"MOV   	R14, R27"        "\n\t"
"LPM   	R24, Z+"         "\n\t"
"LDD   	R31, Y+22"       "\n\t"
"STD   	Z+61, R14"       "\n\t"
"ADC   	R8, R21"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ADIW  	R28, 8"          "\n\t"
"BLD   	R31, 1"          "\n\t"
"STS   	969, R26"        "\n\t"
"AND   	R30, R27"        "\n\t"
"BCLR  	0"               "\n\t"
"SUBI  	R17, 166"        "\n\t"
"LDS   	R7, 1225"        "\n\t"
"ADD   	R19, R16"        "\n\t"
"SBCI  	R29, 227"        "\n\t"
"WDR   	"                "\n\t"
"LSR   	R21"             "\n\t"
"CPC   	R11, R26"        "\n\t"
"MOVW  	R16, R14"        "\n\t"
"SBCI  	R27, 136"        "\n\t"
"SUBI  	R20, 205"        "\n\t"
"LDS   	R13, 935"        "\n\t"
"LDI   	R23, 173"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"WDR   	"                "\n\t"
"NEG   	R10"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ST    	-X, R4"          "\n\t"
"SUB   	R2, R17"         "\n\t"
"LD    	R23, -Z"         "\n\t"
"AND   	R6, R4"          "\n\t"
"SBCI  	R30, 81"         "\n\t"
"FMULSU	R19, R21"        "\n\t"
"MULS  	R20, R22"        "\n\t"
"CPI   	R26, 65"         "\n\t"
"LDD   	R22, Y+16"       "\n\t"
"MULS  	R28, R17"        "\n\t"
"STS   	1847, R24"       "\n\t"
"MOV   	R15, R21"        "\n\t"
"SBC   	R6, R19"         "\n\t"
"MOV   	R19, R28"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"ST    	X+, R11"         "\n\t"
"MULSU 	R23, R19"        "\n\t"
"MULS  	R16, R21"        "\n\t"
"CP    	R5, R29"         "\n\t"
"LPM   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ADD   	R3, R26"         "\n\t"
"IN    	R10, 15"         "\n\t"
"CPI   	R20, 161"        "\n\t"
"BLD   	R0, 4"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"ST    	-Z, R15"         "\n\t"
"ASR   	R7"              "\n\t"
"SWAP  	R9"              "\n\t"
"LPM   	R12, Z"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"LD    	R11, X"          "\n\t"
"MUL   	R26, R0"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"ROR   	R31"             "\n\t"
"LPM   	"                "\n\t"
"BSET  	1"               "\n\t"
"MUL   	R14, R5"         "\n\t"
"SUB   	R26, R20"        "\n\t"
"BLD   	R2, 1"           "\n\t"
"CPC   	R25, R28"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ADC   	R11, R23"        "\n\t"
"LPM   	R13, Z"          "\n\t"
"SBC   	R10, R6"         "\n\t"
"NEG   	R8"              "\n\t"
"SWAP  	R8"              "\n\t"
"CBI   	24, 0"           "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"FMULSU	R17, R20"        "\n\t"
"MULSU 	R20, R16"        "\n\t"
"COM   	R8"              "\n\t"
"SBIS  	1, 1"            "\n\t"
"SBI   	9, 5"            "\n\t"
"SUBI  	R26, 218"        "\n\t"
"LPM   	R18, Z+"         "\n\t"
"MULSU 	R19, R16"        "\n\t"
"COM   	R10"             "\n\t"
"ADC   	R8, R22"         "\n\t"
"FMULSU	R22, R22"        "\n\t"
"NEG   	R25"             "\n\t"
"CPSE  	R1, R12"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BLD   	R0, 1"           "\n\t"
"BSET  	0"               "\n\t"
"WDR   	"                "\n\t"
"SER   	R26"             "\n\t"
"BLD   	R7, 4"           "\n\t"
"SBIC  	3, 1"            "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CBI   	27, 5"           "\n\t"
"ADC   	R13, R30"        "\n\t"
"CPI   	R19, 97"         "\n\t"
"CPSE  	R21, R2"         "\n\t"
"CP    	R23, R24"        "\n\t"
"LDS   	R18, 570"        "\n\t"
"IN    	R3, 7"           "\n\t"
"CALL  	Test_JMP"        "\n\t"
"STS   	1353, R2"        "\n\t"
"COM   	R2"              "\n\t"
"CPC   	R20, R25"        "\n\t"
"SUB   	R13, R22"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"WDR   	"                "\n\t"
"FMUL  	R23, R20"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"FMUL  	R18, R19"        "\n\t"
"OR    	R19, R24"        "\n\t"
"ADC   	R15, R14"        "\n\t"
"ASR   	R13"             "\n\t"
"CBI   	5, 5"            "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"BSET  	7"               "\n\t"
"MULSU 	R21, R19"        "\n\t"
"BST   	R29, 0"          "\n\t"
"SER   	R21"             "\n\t"
"MULSU 	R22, R21"        "\n\t"
"EOR   	R10, R10"        "\n\t"
"LDD   	R10, Y+23"       "\n\t"
"SBRS  	R8, 0"           "\n\t"
"CPI   	R28, 45"         "\n\t"
"CPC   	R24, R8"         "\n\t"
"ADIW  	R28, 44"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CPI   	R24, 133"        "\n\t"
"SER   	R27"             "\n\t"
"FMUL  	R20, R23"        "\n\t"
"CPSE  	R30, R26"        "\n\t"
"MULS  	R24, R16"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"FMULS 	R19, R23"        "\n\t"
"SBIS  	14, 1"           "\n\t"
"ADC   	R28, R25"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"WDR   	"                "\n\t"
"ADIW  	R24, 5"          "\n\t"
"ROR   	R29"             "\n\t"
"AND   	R7, R31"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"WDR   	"                "\n\t"
"LDD   	R3, Y+11"        "\n\t"
"STS   	1442, R17"       "\n\t"
"MULS  	R31, R21"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ADD   	R9, R9"          "\n\t"
"SBCI  	R26, 50"         "\n\t"
"SWAP  	R5"              "\n\t"
"FMULSU	R17, R20"        "\n\t"
"BST   	R7, 4"           "\n\t"
"SUBI  	R18, 245"        "\n\t"
"SUBI  	R18, 250"        "\n\t"
"CPI   	R31, 158"        "\n\t"
"LDI   	R19, 242"        "\n\t"
"CPC   	R2, R21"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SUB   	R17, R4"         "\n\t"
"SUB   	R3, R21"         "\n\t"
"LPM   	"                "\n\t"
"LPM   	"                "\n\t"
"ADC   	R25, R19"        "\n\t"
"AND   	R24, R21"        "\n\t"
"EOR   	R18, R17"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_JMP"        "\n\t"
"ROR   	R30"             "\n\t"
"CPI   	R17, 90"         "\n\t"
"SBC   	R6, R18"         "\n\t"
"AND   	R2, R26"         "\n\t"
"ST    	-X, R7"          "\n\t"
"BLD   	R28, 7"          "\n\t"
"SBRC  	R22, 2"          "\n\t"
"MOVW  	R0, R26"         "\n\t"
"STS   	314, R21"        "\n\t"
"CPSE  	R27, R4"         "\n\t"
"CPC   	R22, R17"        "\n\t"
"FMUL  	R19, R23"        "\n\t"
"LDI   	R28, 130"        "\n\t"
"FMULS 	R21, R23"        "\n\t"
"EOR   	R8, R18"         "\n\t"
"LDD   	R26, Z+5"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"WDR   	"                "\n\t"
"FMULS 	R23, R18"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CPI   	R28, 13"         "\n\t"
"ADD   	R8, R25"         "\n\t"
"SUB   	R22, R24"        "\n\t"
"ROR   	R12"             "\n\t"
"ROR   	R17"             "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CPI   	R29, 31"         "\n\t"
"BST   	R7, 0"           "\n\t"
"ROR   	R6"              "\n\t"
"AND   	R26, R27"        "\n\t"
"NEG   	R4"              "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"COM   	R10"             "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"ST    	X+, R16"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SBIC  	18, 3"           "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBIC  	20, 7"           "\n\t"
"NEG   	R27"             "\n\t"
"ASR   	R14"             "\n\t"
"ADIW  	R28, 33"         "\n\t"
"SBIC  	10, 4"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"MUL   	R4, R18"         "\n\t"
"COM   	R1"              "\n\t"
"EOR   	R1, R19"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ADC   	R10, R1"         "\n\t"
"MULSU 	R18, R18"        "\n\t"
"COM   	R1"              "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CPSE  	R10, R22"        "\n\t"
"FMULSU	R18, R17"        "\n\t"
"MULS  	R23, R18"        "\n\t"
"FMULSU	R23, R17"        "\n\t"
"LD    	R1, Z"           "\n\t"
"NEG   	R3"              "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SUBI  	R18, 3"          "\n\t"
"MULS  	R21, R25"        "\n\t"
"FMUL  	R16, R16"        "\n\t"
"ROR   	R13"             "\n\t"
"SWAP  	R3"              "\n\t"
"EOR   	R17, R29"        "\n\t"
"BSET  	2"               "\n\t"
"STD   	Z+31, R19"       "\n\t"
"ADD   	R10, R20"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"COM   	R13"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SBRC  	R7, 1"           "\n\t"
"MULS  	R19, R28"        "\n\t"
"CPSE  	R4, R24"         "\n\t"
"OR    	R20, R21"        "\n\t"
"FMULSU	R17, R22"        "\n\t"
"WDR   	"                "\n\t"
"SER   	R18"             "\n\t"
"STS   	1391, R18"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ADD   	R29, R13"        "\n\t"
"MULSU 	R17, R16"        "\n\t"
"ORI   	R25, 104"        "\n\t"
"STD   	Z+59, R16"       "\n\t"
"ANDI  	R26, 4"          "\n\t"
"ANDI  	R18, 178"        "\n\t"
"WDR   	"                "\n\t"
"SBRC  	R24, 3"          "\n\t"
"MUL   	R14, R25"        "\n\t"
"LPM   	R14, Z+"         "\n\t"
"CPC   	R3, R27"         "\n\t"
"BCLR  	3"               "\n\t"
"ASR   	R0"              "\n\t"
"SUBI  	R30, 37"         "\n\t"
"LDS   	R0, 2098"        "\n\t"
"BSET  	2"               "\n\t"
"BCLR  	6"               "\n\t"
"ANDI  	R21, 47"         "\n\t"
"SBIC  	26, 6"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_JMP"        "\n\t"
"OR    	R7, R27"         "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"BLD   	R23, 1"          "\n\t"
"SBIC  	13, 3"           "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CBI   	7, 3"            "\n\t"
"SBI   	9, 4"            "\n\t"
"LD    	R7, Z+"          "\n\t"
"BLD   	R23, 2"          "\n\t"
"BCLR  	0"               "\n\t"
"SBRC  	R20, 2"          "\n\t"
"SUB   	R27, R7"         "\n\t"
"SBIS  	27, 0"           "\n\t"
"WDR   	"                "\n\t"
"OR    	R16, R27"        "\n\t"
"ORI   	R21, 108"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"BLD   	R3, 3"           "\n\t"
"WDR   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"FMUL  	R20, R21"        "\n\t"
"ROR   	R24"             "\n\t"
"SBRS  	R27, 3"          "\n\t"
"CALL  	Test_CALL"       "\n\t"
"LPM   	R1, Z"           "\n\t"
"LSR   	R7"              "\n\t"
"SBCI  	R29, 44"         "\n\t"
"NEG   	R18"             "\n\t"
"LSR   	R6"              "\n\t"
"MUL   	R3, R20"         "\n\t"
"SBC   	R14, R27"        "\n\t"
"ADD   	R22, R20"        "\n\t"
"LPM   	R24, Z+"         "\n\t"
"MUL   	R6, R21"         "\n\t"
"AND   	R18, R12"        "\n\t"
"SBCI  	R26, 158"        "\n\t"
"LDS   	R1, 689"         "\n\t"
"SER   	R22"             "\n\t"
"LPM   	R20, Z+"         "\n\t"
"OR    	R14, R7"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"WDR   	"                "\n\t"
"ADC   	R24, R10"        "\n\t"
"CPC   	R30, R29"        "\n\t"
"CBI   	27, 3"           "\n\t"
"STD   	Y+26, R7"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CPI   	R25, 17"         "\n\t"
"WDR   	"                "\n\t"
"EOR   	R12, R15"        "\n\t"
"WDR   	"                "\n\t"
"CPI   	R18, 82"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"ST    	Z, R3"           "\n\t"
"LD    	R21, -Z"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBRS  	R20, 4"          "\n\t"
"LD    	R7, -Z"          "\n\t"
"ANDI  	R23, 214"        "\n\t"
"EOR   	R16, R25"        "\n\t"
"MULSU 	R18, R20"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"BST   	R12, 6"          "\n\t"
"ADC   	R11, R14"        "\n\t"
"ASR   	R26"             "\n\t"
"SBIC  	25, 1"           "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"MULSU 	R21, R23"        "\n\t"
"ASR   	R31"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"FMULSU	R20, R20"        "\n\t"
"LD    	R2, -Y"          "\n\t"
"BLD   	R9, 4"           "\n\t"
"SUB   	R1, R18"         "\n\t"
"FMUL  	R17, R16"        "\n\t"
"ANDI  	R31, 126"        "\n\t"
"SWAP  	R24"             "\n\t"
"MULSU 	R19, R20"        "\n\t"
"WDR   	"                "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CPSE  	R19, R12"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_JMP"        "\n\t"
"AND   	R3, R25"         "\n\t"
"MOV   	R18, R26"        "\n\t"
"CBI   	14, 7"           "\n\t"
"SBI   	17, 3"           "\n\t"
"LDD   	R24, Y+54"       "\n\t"
"LD    	R23, Z+"         "\n\t"
"LDI   	R29, 177"        "\n\t"
"FMULSU	R22, R19"        "\n\t"
"SBC   	R9, R1"          "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CBI   	14, 6"           "\n\t"
"CPSE  	R26, R23"        "\n\t"
"SBI   	1, 0"            "\n\t"
"SBC   	R3, R6"          "\n\t"
"STS   	1178, R11"       "\n\t"
"NEG   	R19"             "\n\t"
"LSR   	R22"             "\n\t"
"SBRS  	R28, 5"          "\n\t"
"ANDI  	R19, 64"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"COM   	R24"             "\n\t"
"BSET  	0"               "\n\t"
"COM   	R31"             "\n\t"
"SER   	R21"             "\n\t"
"ASR   	R16"             "\n\t"
"SBRS  	R4, 5"           "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LD    	R21, X"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SUB   	R13, R4"         "\n\t"
"SBCI  	R29, 123"        "\n\t"
"OR    	R26, R9"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SWAP  	R5"              "\n\t"
"SUBI  	R27, 88"         "\n\t"
"BLD   	R5, 0"           "\n\t"
"SWAP  	R15"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBIC  	18, 4"           "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"NEG   	R29"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"BLD   	R8, 7"           "\n\t"
"SUB   	R26, R13"        "\n\t"
"SBRS  	R16, 1"          "\n\t"
"SBCI  	R16, 203"        "\n\t"
"CBI   	26, 6"           "\n\t"
"ADD   	R1, R30"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"SBIC  	28, 4"           "\n\t"
"SER   	R25"             "\n\t"
"CALL  	Test_JMP"        "\n\t"
"LPM   	R27, Z+"         "\n\t"
"SWAP  	R5"              "\n\t"
"BCLR  	5"               "\n\t"
"FMULS 	R19, R19"        "\n\t"
"LSR   	R8"              "\n\t"
"CPC   	R21, R8"         "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"FMULS 	R21, R17"        "\n\t"
"IN    	R0, 45"          "\n\t"
"AND   	R15, R2"         "\n\t"
"AND   	R31, R3"         "\n\t"
"MOVW  	R10, R10"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ADC   	R5, R8"          "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CPI   	R29, 155"        "\n\t"
"SBIS  	26, 4"           "\n\t"
"CPI   	R28, 127"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"COM   	R10"             "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CALL  	Test_CALL"       "\n\t"
"MULSU 	R22, R23"        "\n\t"
"ORI   	R19, 231"        "\n\t"
"FMUL  	R23, R22"        "\n\t"
"LDI   	R19, 51"         "\n\t"
"ADIW  	R24, 5"          "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CPSE  	R30, R23"        "\n\t"
"MULS  	R23, R24"        "\n\t"
"OR    	R24, R22"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"ST    	X, R5"           "\n\t"
"ANDI  	R28, 115"        "\n\t"
"SUBI  	R29, 97"         "\n\t"
"SBC   	R8, R27"         "\n\t"
"MOVW  	R16, R22"        "\n\t"
"SBIS  	8, 4"            "\n\t"
"CALL  	Test_CALL"       "\n\t"
"BLD   	R28, 5"          "\n\t"
"AND   	R21, R29"        "\n\t"
"AND   	R25, R28"        "\n\t"
"BLD   	R16, 2"          "\n\t"
"AND   	R7, R28"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"FMULSU	R23, R17"        "\n\t"
"BCLR  	3"               "\n\t"
"AND   	R13, R11"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SER   	R16"             "\n\t"
"SBI   	19, 0"           "\n\t"
"WDR   	"                "\n\t"
"ADD   	R7, R28"         "\n\t"
"CPC   	R26, R27"        "\n\t"
"ANDI  	R20, 213"        "\n\t"
"SBRC  	R20, 2"          "\n\t"
"WDR   	"                "\n\t"
"MULSU 	R21, R20"        "\n\t"
"LPM   	R5, Z+"          "\n\t"
"EOR   	R0, R11"         "\n\t"
"BSET  	5"               "\n\t"
"SWAP  	R27"             "\n\t"
"OR    	R3, R13"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"OR    	R22, R19"        "\n\t"
"LSR   	R15"             "\n\t"
"SUBI  	R16, 191"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"ANDI  	R27, 251"        "\n\t"
"CPC   	R0, R19"         "\n\t"
"STS   	383, R8"         "\n\t"
"FMULSU	R20, R22"        "\n\t"
"SBCI  	R25, 215"        "\n\t"
"LDD   	R19, Z+6"        "\n\t"
"BST   	R17, 4"          "\n\t"
"SBIS  	26, 6"           "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"BLD   	R5, 7"           "\n\t"
"SBC   	R26, R9"         "\n\t"
"SER   	R22"             "\n\t"
"AND   	R25, R12"        "\n\t"
"SUB   	R17, R7"         "\n\t"
"LDS   	R26, 1665"       "\n\t"
"STS   	706, R27"        "\n\t"
"IN    	R31, 1"          "\n\t"
"WDR   	"                "\n\t"
"SBRS  	R28, 7"          "\n\t"
"WDR   	"                "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CPI   	R16, 254"        "\n\t"
"SBIC  	10, 3"           "\n\t"
"FMULSU	R20, R19"        "\n\t"
"LDS   	R14, 821"        "\n\t"
"LSR   	R9"              "\n\t"
"MULS  	R28, R16"        "\n\t"
"MUL   	R18, R15"        "\n\t"
"IN    	R6, 59"          "\n\t"
"LDD   	R18, Y+16"       "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"LDS   	R2, 511"         "\n\t"
"LPM   	"                "\n\t"
"LSR   	R29"             "\n\t"
"SBI   	30, 2"           "\n\t"
"NEG   	R5"              "\n\t"
"SBI   	3, 0"            "\n\t"
"AND   	R3, R16"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"LDD   	R29, Z+12"       "\n\t"
"ADD   	R12, R31"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
