"OR    	R24, R0"         "\n\t"
"CPI   	R22, 93"         "\n\t"
"SER   	R20"             "\n\t"
"CPSE  	R10, R1"         "\n\t"
"NEG   	R13"             "\n\t"
"LPM   	"                "\n\t"
"MUL   	R3, R8"          "\n\t"
"MULS  	R25, R26"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CP    	R4, R8"          "\n\t"
"ADIW  	R28, 35"         "\n\t"
"OUT   	63, R14"         "\n\t"
"PUSH  	R3"              "\n\t"
"BSET  	0"               "\n\t"
"LSR   	R0"              "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LDD   	R30, Y+20"       "\n\t"
"LPM   	R19, Z+"         "\n\t"
"CPC   	R16, R25"        "\n\t"
"LD    	R15, Z"          "\n\t"
"SBI   	18, 6"           "\n\t"
"CP    	R3, R18"         "\n\t"
"LDS   	R0, 914"         "\n\t"
"MUL   	R18, R21"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CP    	R21, R17"        "\n\t"
"POP   	R30"             "\n\t"
"SWAP  	R0"              "\n\t"
"LDI   	R16, 246"        "\n\t"
"BST   	R1, 3"           "\n\t"
"CBI   	12, 1"           "\n\t"
"CPC   	R29, R8"         "\n\t"
"EOR   	R8, R21"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SWAP  	R18"             "\n\t"
"CPI   	R18, 155"        "\n\t"
"CBI   	13, 2"           "\n\t"
"POP   	R17"             "\n\t"
"SUBI  	R28, 125"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"LPM   	"                "\n\t"
"ADD   	R0, R15"         "\n\t"
"ROR   	R26"             "\n\t"
"LSR   	R13"             "\n\t"
"CBI   	2, 1"            "\n\t"
"SBIC  	7, 1"            "\n\t"
"LDD   	R30, Z+42"       "\n\t"
"MUL   	R7, R28"         "\n\t"
"ST    	X, R25"          "\n\t"
"NEG   	R10"             "\n\t"
"CPC   	R10, R1"         "\n\t"
"LDD   	R9, Y+3"         "\n\t"
"AND   	R21, R7"         "\n\t"
"FMUL  	R18, R18"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"LD    	R18, Y+"         "\n\t"
"ADC   	R3, R30"         "\n\t"
"BSET  	0"               "\n\t"
"OUT   	22, R12"         "\n\t"
"SBI   	6, 0"            "\n\t"
"SUBI  	R21, 254"        "\n\t"
"SBI   	23, 5"           "\n\t"
"ADC   	R22, R25"        "\n\t"
"CBI   	4, 1"            "\n\t"
"CPSE  	R1, R6"          "\n\t"
"SBC   	R22, R22"        "\n\t"
"LSR   	R28"             "\n\t"
"LPM   	R24, Z+"         "\n\t"
"OUT   	45, R9"          "\n\t"
"FMULS 	R16, R22"        "\n\t"
"LPM   	"                "\n\t"
"IN    	R16, 17"         "\n\t"
"ROR   	R24"             "\n\t"
"FMULSU	R19, R21"        "\n\t"
"LSR   	R15"             "\n\t"
"BCLR  	2"               "\n\t"
"CP    	R4, R24"         "\n\t"
"SWAP  	R31"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"LSR   	R21"             "\n\t"
"SBCI  	R16, 65"         "\n\t"
"FMUL  	R19, R23"        "\n\t"
"LPM   	R19, Z"          "\n\t"
"SUB   	R31, R14"        "\n\t"
"BST   	R5, 3"           "\n\t"
"SBIC  	6, 3"            "\n\t"
"BST   	R8, 1"           "\n\t"
"CALL  	Test_CALL"       "\n\t"
"COM   	R29"             "\n\t"
"SBRC  	R21, 5"          "\n\t"
"IN    	R12, 9"          "\n\t"
"SBI   	7, 7"            "\n\t"
"ADC   	R31, R3"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_CALL"       "\n\t"
"BLD   	R2, 2"           "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBRC  	R4, 6"           "\n\t"
"SER   	R19"             "\n\t"
"ASR   	R10"             "\n\t"
"SBIC  	14, 1"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"COM   	R2"              "\n\t"
"SBC   	R18, R17"        "\n\t"
"LDI   	R24, 240"        "\n\t"
"ROR   	R4"              "\n\t"
"LDD   	R1, Z+35"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ASR   	R20"             "\n\t"
"MULS  	R25, R26"        "\n\t"
"LDD   	R2, Z+35"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"EOR   	R10, R7"         "\n\t"
"BLD   	R15, 5"          "\n\t"
"STD   	Y+22, R2"        "\n\t"
"SBC   	R17, R16"        "\n\t"
"ST    	Z+, R20"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SWAP  	R4"              "\n\t"
"AND   	R23, R14"        "\n\t"
"PUSH  	R18"             "\n\t"
"LDI   	R24, 114"        "\n\t"
"LD    	R25, -Z"         "\n\t"
"FMULSU	R19, R17"        "\n\t"
"SER   	R19"             "\n\t"
"CPSE  	R31, R26"        "\n\t"
"MOV   	R0, R25"         "\n\t"
"BSET  	7"               "\n\t"
"POP   	R11"             "\n\t"
"SBC   	R10, R13"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"COM   	R31"             "\n\t"
"LDI   	R23, 86"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LDI   	R20, 213"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"OR    	R22, R9"         "\n\t"
"PUSH  	R20"             "\n\t"
"CPSE  	R22, R12"        "\n\t"
"POP   	R11"             "\n\t"
"LDS   	R13, 2257"       "\n\t"
"EOR   	R1, R18"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LDI   	R31, 63"         "\n\t"
"STD   	Y+44, R14"       "\n\t"
"NEG   	R16"             "\n\t"
"MOV   	R2, R7"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CPI   	R19, 80"         "\n\t"
"OUT   	2, R26"          "\n\t"
"MOVW  	R22, R18"        "\n\t"
"MOVW  	R26, R28"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"PUSH  	R16"             "\n\t"
"LDI   	R16, 164"        "\n\t"
"CPI   	R31, 161"        "\n\t"
"MUL   	R17, R2"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SBI   	14, 0"           "\n\t"
"LSR   	R30"             "\n\t"
"MOV   	R28, R30"        "\n\t"
"CBI   	22, 7"           "\n\t"
"AND   	R6, R26"         "\n\t"
"SBRC  	R10, 7"          "\n\t"
"MOV   	R17, R20"        "\n\t"
"MUL   	R0, R6"          "\n\t"
"MOVW  	R8, R22"         "\n\t"
"CPC   	R8, R25"         "\n\t"
"SBRC  	R12, 2"          "\n\t"
"LDS   	R17, 1676"       "\n\t"
"CPSE  	R15, R13"        "\n\t"
"SBCI  	R22, 69"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"ROR   	R7"              "\n\t"
"FMUL  	R20, R19"        "\n\t"
"STS   	2125, R0"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"STS   	2187, R15"       "\n\t"
"OUT   	58, R29"         "\n\t"
"BST   	R6, 6"           "\n\t"
"BLD   	R14, 5"          "\n\t"
"NEG   	R14"             "\n\t"
"SWAP  	R28"             "\n\t"
"OUT   	5, R0"           "\n\t"
"CBI   	30, 5"           "\n\t"
"FMUL  	R19, R17"        "\n\t"
"ANDI  	R22, 227"        "\n\t"
"SBC   	R28, R17"        "\n\t"
"SBCI  	R20, 232"        "\n\t"
"SBIS  	8, 0"            "\n\t"
"FMUL  	R23, R20"        "\n\t"
"STD   	Z+12, R9"        "\n\t"
"BSET  	2"               "\n\t"
"CBI   	21, 4"           "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"OR    	R29, R28"        "\n\t"
"CPC   	R29, R2"         "\n\t"
"IN    	R11, 29"         "\n\t"

// "LDI	R16, 0x69"		"\n\t"
// "STS	0x26F, R16"		"\n\t"

"OR    	R5, R19"         "\n\t"
"NEG   	R0"              "\n\t"
"PUSH  	R0"              "\n\t"
"STD   	Y+15, R4"        "\n\t"
"BLD   	R14, 7"          "\n\t"
"BST   	R30, 5"          "\n\t"
"BLD   	R13, 6"          "\n\t"
"CP    	R8, R31"         "\n\t"
"LD    	R3, Y"           "\n\t"
"LD    	R1, Z"           "\n\t"
"SUBI  	R26, 27"         "\n\t"
"SBIS  	17, 1"           "\n\t"
"SBI   	11, 7"           "\n\t"
"MUL   	R2, R14"         "\n\t"
"MULSU 	R17, R16"        "\n\t"
"SBI   	28, 0"           "\n\t"
"ANDI  	R18, 207"        "\n\t"
"BSET  	3"               "\n\t"
"ADIW  	R24, 33"         "\n\t"
"AND   	R23, R25"        "\n\t"
"ADIW  	R30, 40"         "\n\t"
"OUT   	42, R26"         "\n\t"
"COM   	R21"             "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"BLD   	R11, 4"          "\n\t"
"MOVW  	R0, R20"         "\n\t"
"PUSH  	R21"             "\n\t"
"ST    	-X, R16"         "\n\t"
"MOVW  	R14, R14"        "\n\t"
"SBRC  	R11, 1"          "\n\t"
"CALL  	Test_JMP"        "\n\t"
"FMULS 	R22, R16"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"BLD   	R3, 0"           "\n\t"
"FMULS 	R20, R20"        "\n\t"
"AND   	R13, R11"        "\n\t"
"SBIC  	3, 2"            "\n\t"
"PUSH  	R3"              "\n\t"
"ADIW  	R26, 49"         "\n\t"
"CPC   	R31, R24"        "\n\t"
"MULS  	R20, R22"        "\n\t"
"CPI   	R31, 70"         "\n\t"
"COM   	R28"             "\n\t"
"LSR   	R8"              "\n\t"
"CPC   	R15, R30"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"FMUL  	R19, R16"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"AND   	R31, R20"        "\n\t"
"MOV   	R25, R27"        "\n\t"
"SBC   	R24, R30"        "\n\t"
"SBI   	1, 4"            "\n\t"
"LDI   	R23, 201"        "\n\t"
"ROR   	R7"              "\n\t"
"CALL  	Test_JMP"        "\n\t"
"MUL   	R30, R8"         "\n\t"
"PUSH  	R6"              "\n\t"
"ST    	Z, R13"          "\n\t"
"BST   	R2, 6"           "\n\t"
"AND   	R31, R19"        "\n\t"
"LDI   	R23, 152"        "\n\t"
"CPC   	R24, R9"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"PUSH  	R13"             "\n\t"
"SBC   	R19, R7"         "\n\t"
"COM   	R14"             "\n\t"
"FMUL  	R22, R18"        "\n\t"
"LDD   	R23, Z+57"       "\n\t"
"MULS  	R22, R31"        "\n\t"
"SBRC  	R27, 3"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"FMULS 	R20, R18"        "\n\t"
"LPM   	R25, Z+"         "\n\t"
"ANDI  	R21, 244"        "\n\t"
"CPI   	R20, 20"         "\n\t"
"BLD   	R15, 2"          "\n\t"
"LDD   	R13, Z+49"       "\n\t"
"PUSH  	R27"             "\n\t"
"LDI   	R18, 97"         "\n\t"
"ROR   	R11"             "\n\t"
"AND   	R25, R2"         "\n\t"
"BST   	R27, 6"          "\n\t"
"NEG   	R20"             "\n\t"
"BST   	R27, 5"          "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"LSR   	R0"              "\n\t"
"STS   	1110, R11"       "\n\t"
"EOR   	R4, R1"          "\n\t"
"ASR   	R11"             "\n\t"
"STS   	433, R20"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"ASR   	R0"              "\n\t"
"CALL  	Test_CALL"       "\n\t"
"BST   	R15, 5"          "\n\t"
"LDI   	R22, 12"         "\n\t"
"STD   	Z+11, R1"        "\n\t"
"CP    	R0, R15"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"MULSU 	R20, R21"        "\n\t"
"ORI   	R19, 156"        "\n\t"
"OUT   	36, R18"         "\n\t"
"LDS   	R19, 906"        "\n\t"
"OR    	R8, R1"          "\n\t"
"LDI   	R31, 224"        "\n\t"
"LDS   	R13, 1290"       "\n\t"
"SUB   	R9, R0"          "\n\t"
"OUT   	51, R27"         "\n\t"
"MOV   	R16, R5"         "\n\t"
"SER   	R17"             "\n\t"
"LDS   	R27, 393"        "\n\t"
"STD   	Y+24, R18"       "\n\t"
"STD   	Y+33, R21"       "\n\t"
"MULS  	R22, R30"        "\n\t"
"AND   	R26, R10"        "\n\t"
"SBI   	11, 7"           "\n\t"
"SBRC  	R19, 6"          "\n\t"
"POP   	R24"             "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"FMULSU	R20, R21"        "\n\t"
"MOV   	R16, R25"        "\n\t"
"MULS  	R20, R17"        "\n\t"
"ASR   	R4"              "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SUBI  	R26, 145"        "\n\t"
"ADD   	R0, R4"          "\n\t"
"SUBI  	R30, 84"         "\n\t"
"POP   	R30"             "\n\t"
"BLD   	R29, 3"          "\n\t"
"MOVW  	R14, R28"        "\n\t"
"PUSH  	R4"              "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"SUB   	R29, R1"         "\n\t"
"AND   	R24, R28"        "\n\t"
"MOV   	R8, R14"         "\n\t"
"EOR   	R1, R6"          "\n\t"
"STS   	781, R24"        "\n\t"
"ROR   	R10"             "\n\t"
"LSR   	R7"              "\n\t"
"SBRS  	R31, 5"          "\n\t"
"MOVW  	R20, R28"        "\n\t"
"NEG   	R0"              "\n\t"
"ST    	-Y, R2"          "\n\t"
"CALL  	Test_JMP"        "\n\t"
"SBIC  	22, 4"           "\n\t"
"BCLR  	3"               "\n\t"
"STD   	Y+37, R9"        "\n\t"
"NEG   	R9"              "\n\t"
"LSR   	R28"             "\n\t"
"MOV   	R21, R13"        "\n\t"
"COM   	R2"              "\n\t"
"FMUL  	R17, R23"        "\n\t"
"SUB   	R11, R14"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"LDI   	R31, 90"         "\n\t"
"LD    	R21, Z+"         "\n\t"
"SBC   	R13, R6"         "\n\t"
"CPC   	R8, R29"         "\n\t"
"FMULSU	R19, R17"        "\n\t"
"ROR   	R30"             "\n\t"
"FMULS 	R23, R22"        "\n\t"
"FMUL  	R21, R18"        "\n\t"
"ASR   	R0"              "\n\t"
"AND   	R9, R2"          "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"ANDI  	R31, 169"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"AND   	R14, R17"        "\n\t"
"ADIW  	R28, 42"         "\n\t"
"POP   	R26"             "\n\t"
"LD    	R17, Y+"         "\n\t"
"CP    	R3, R30"         "\n\t"
"ADC   	R18, R23"        "\n\t"
"BCLR  	0"               "\n\t"
"CP    	R4, R20"         "\n\t"
"BST   	R3, 7"           "\n\t"
"LDD   	R25, Y+48"       "\n\t"
"FMULSU	R20, R16"        "\n\t"
"LD    	R4, Z"           "\n\t"
"ANDI  	R17, 103"        "\n\t"
"CPSE  	R9, R4"          "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"CPI   	R24, 118"        "\n\t"
"ADD   	R4, R25"         "\n\t"
"FMULSU	R16, R17"        "\n\t"
"CPSE  	R15, R25"        "\n\t"
"ASR   	R5"              "\n\t"
"POP   	R1"              "\n\t"
"ADIW  	R24, 60"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"LD    	R4, X"           "\n\t"
"COM   	R2"              "\n\t"
"SBRC  	R18, 1"          "\n\t"
"ORI   	R21, 78"         "\n\t"
"POP   	R25"             "\n\t"
"CPC   	R26, R28"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"EOR   	R6, R19"         "\n\t"
"AND   	R3, R2"          "\n\t"
"SER   	R20"             "\n\t"
"MUL   	R3, R1"          "\n\t"
"SUBI  	R28, 95"         "\n\t"
"LDS   	R6, 355"         "\n\t"
"SUB   	R26, R28"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"LD    	R13, -X"         "\n\t"
"SWAP  	R21"             "\n\t"
"EOR   	R12, R31"        "\n\t"
"SER   	R17"             "\n\t"
"MOVW  	R14, R22"        "\n\t"
"SER   	R17"             "\n\t"
"OR    	R8, R27"         "\n\t"
"STS   	1694, R14"       "\n\t"
"CPI   	R18, 40"         "\n\t"
"COM   	R27"             "\n\t"
"MOVW  	R24, R18"        "\n\t"
"AND   	R12, R14"        "\n\t"
"SER   	R24"             "\n\t"
"SBCI  	R19, 12"         "\n\t"
"LPM   	"                "\n\t"
"STS   	403, R17"        "\n\t"
"SBCI  	R29, 240"        "\n\t"
"CBI   	17, 6"           "\n\t"
"SBRS  	R14, 1"          "\n\t"
"ADD   	R23, R0"         "\n\t"
"CP    	R22, R8"         "\n\t"
"ADIW  	R26, 63"         "\n\t"
"LPM   	R26, Z+"         "\n\t"
"SUBI  	R20, 191"        "\n\t"
"BSET  	1"               "\n\t"
"SBIC  	31, 6"           "\n\t"
"CPSE  	R24, R16"        "\n\t"
"LDI   	R20, 221"        "\n\t"
"MULS  	R22, R28"        "\n\t"
"NEG   	R7"              "\n\t"
"ASR   	R23"             "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SBIC  	29, 3"           "\n\t"
"LDI   	R17, 250"        "\n\t"
"CP    	R3, R22"         "\n\t"
"ASR   	R16"             "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"OUT   	12, R31"         "\n\t"
"STD   	Y+7, R3"         "\n\t"
"ADD   	R1, R24"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"STD   	Z+47, R29"       "\n\t"
"MULS  	R26, R26"        "\n\t"
"FMULS 	R19, R21"        "\n\t"
"BST   	R16, 4"          "\n\t"
"SWAP  	R30"             "\n\t"
"SBCI  	R26, 149"        "\n\t"
"LSR   	R28"             "\n\t"
"LDD   	R14, Z+40"       "\n\t"
"ADC   	R29, R8"         "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBCI  	R24, 198"        "\n\t"
"CPC   	R4, R2"          "\n\t"
"ADIW  	R26, 12"         "\n\t"
"MOVW  	R26, R22"        "\n\t"
"ADD   	R13, R13"        "\n\t"
"SBI   	14, 5"           "\n\t"
"POP   	R8"              "\n\t"
"ADIW  	R24, 31"         "\n\t"
"POP   	R8"              "\n\t"
"FMULSU	R19, R22"        "\n\t"
"AND   	R21, R27"        "\n\t"
"FMUL  	R17, R20"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"MOVW  	R8, R24"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SBCI  	R28, 10"         "\n\t"
"BST   	R17, 6"          "\n\t"
"LD    	R25, Z"          "\n\t"
"BLD   	R18, 3"          "\n\t"
"NEG   	R22"             "\n\t"
"SBRC  	R21, 0"          "\n\t"
"SER   	R31"             "\n\t"
"BSET  	5"               "\n\t"
"POP   	R18"             "\n\t"
"SBRS  	R31, 5"          "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"ADC   	R14, R17"        "\n\t"
"IN    	R9, 2"           "\n\t"
"BLD   	R22, 6"          "\n\t"
"LPM   	R22, Z"          "\n\t"
"FMULSU	R22, R20"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"ADIW  	R24, 32"         "\n\t"
"LD    	R19, X+"         "\n\t"
"OUT   	22, R18"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"ANDI  	R18, 230"        "\n\t"
"SWAP  	R5"              "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"ST    	Z+, R23"         "\n\t"
"FMULSU	R19, R16"        "\n\t"
"BST   	R28, 5"          "\n\t"
"MOV   	R20, R18"        "\n\t"
"FMULS 	R20, R20"        "\n\t"
"LDD   	R2, Z+42"        "\n\t"
"ORI   	R17, 66"         "\n\t"
"CBI   	6, 0"            "\n\t"
"ADD   	R9, R3"          "\n\t"
"CP    	R4, R12"         "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"PUSH  	R15"             "\n\t"
"FMULSU	R19, R17"        "\n\t"
"ADC   	R8, R28"         "\n\t"
"OR    	R10, R19"        "\n\t"
"SBCI  	R25, 218"        "\n\t"
"COM   	R23"             "\n\t"
"MOV   	R3, R3"          "\n\t"
"MOV   	R30, R27"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"ANDI  	R23, 162"        "\n\t"
"LDI   	R31, 59"         "\n\t"
"ORI   	R29, 241"        "\n\t"
"LSR   	R24"             "\n\t"
"MOV   	R30, R7"         "\n\t"
"FMULSU	R18, R23"        "\n\t"
"LD    	R2, -Y"          "\n\t"
"SUBI  	R17, 176"        "\n\t"
"MUL   	R16, R29"        "\n\t"
"LDD   	R29, Y+4"        "\n\t"
"ADD   	R17, R6"         "\n\t"
"SBIS  	4, 5"            "\n\t"
"CPI   	R27, 77"         "\n\t"
"CPSE  	R15, R0"         "\n\t"
"STD   	Z+30, R14"       "\n\t"
"STD   	Z+24, R0"        "\n\t"
"LPM   	"                "\n\t"
"SBC   	R27, R0"         "\n\t"
"LPM   	"                "\n\t"
"ASR   	R8"              "\n\t"
"PUSH  	R11"             "\n\t"
"BSET  	1"               "\n\t"
"ASR   	R3"              "\n\t"
"OR    	R21, R15"        "\n\t"
"SBRS  	R2, 6"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SWAP  	R2"              "\n\t"
"CPI   	R30, 184"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"ADC   	R19, R31"        "\n\t"
"ST    	Y, R1"           "\n\t"
"FMUL  	R23, R17"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"ANDI  	R19, 55"         "\n\t"
"FMUL  	R22, R22"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"POP   	R3"              "\n\t"
"LPM   	R27, Z+"         "\n\t"
"MULSU 	R17, R23"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"BCLR  	4"               "\n\t"
"BLD   	R11, 4"          "\n\t"
"PUSH  	R28"             "\n\t"
"OUT   	41, R24"         "\n\t"
"AND   	R5, R20"         "\n\t"
"LSR   	R14"             "\n\t"
"ANDI  	R28, 117"        "\n\t"
"SBIC  	25, 1"           "\n\t"
"CALL  	Test_CALL"       "\n\t"
"ROR   	R15"             "\n\t"
"LDI   	R31, 126"        "\n\t"
"BCLR  	1"               "\n\t"
"AND   	R22, R23"        "\n\t"
"AND   	R17, R28"        "\n\t"
"SWAP  	R11"             "\n\t"
"BST   	R24, 0"          "\n\t"
"SUB   	R22, R4"         "\n\t"
"BSET  	4"               "\n\t"
"LDS   	R29, 1834"       "\n\t"
"STD   	Y+30, R20"       "\n\t"
"ANDI  	R22, 227"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"ASR   	R30"             "\n\t"
"SWAP  	R9"              "\n\t"
"CBI   	1, 7"            "\n\t"
"SBCI  	R27, 230"        "\n\t"
"MOVW  	R16, R14"        "\n\t"
"CPC   	R6, R2"          "\n\t"
"SBRS  	R23, 2"          "\n\t"
"LD    	R22, Y+"         "\n\t"
"MULS  	R28, R19"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"SBRC  	R24, 5"          "\n\t"
"ANDI  	R18, 28"         "\n\t"
"SBC   	R9, R17"         "\n\t"
"MULS  	R30, R29"        "\n\t"
"CPSE  	R12, R7"         "\n\t"
"CPC   	R13, R28"        "\n\t"
"LDS   	R7, 636"         "\n\t"
"LSR   	R11"             "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"SBIS  	24, 7"           "\n\t"
"OR    	R28, R3"         "\n\t"
"SBRC  	R1, 2"           "\n\t"
"POP   	R21"             "\n\t"
"SBCI  	R18, 175"        "\n\t"
"SWAP  	R29"             "\n\t"
"MULSU 	R21, R23"        "\n\t"
"MULSU 	R22, R16"        "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"BSET  	3"               "\n\t"
"CPI   	R23, 135"        "\n\t"
"FMULSU	R23, R18"        "\n\t"
"LPM   	"                "\n\t"
"IN    	R14, 12"         "\n\t"
"ORI   	R25, 80"         "\n\t"
"BLD   	R15, 0"          "\n\t"
"STD   	Z+50, R14"       "\n\t"
"POP   	R12"             "\n\t"
"ROR   	R30"             "\n\t"
"SBRC  	R12, 2"          "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CALL  	Test_JMP"        "\n\t"
"BLD   	R15, 0"          "\n\t"
"ROR   	R29"             "\n\t"
"STS   	1199, R12"       "\n\t"
"NEG   	R20"             "\n\t"
"PUSH  	R28"             "\n\t"
"POP   	R15"             "\n\t"
"FMULS 	R19, R21"        "\n\t"
"SBC   	R10, R31"        "\n\t"
"BSET  	0"               "\n\t"
"LDS   	R16, 2181"       "\n\t"
"SBRS  	R5, 4"           "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"AND   	R0, R17"         "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"LSR   	R29"             "\n\t"
"EOR   	R12, R1"         "\n\t"
"BCLR  	1"               "\n\t"
"SBRC  	R26, 4"          "\n\t"
"SBI   	5, 3"            "\n\t"
"ADIW  	R30, 1"          "\n\t"
"SBRC  	R28, 4"          "\n\t"
"MOVW  	R0, R8"          "\n\t"
"OR    	R6, R9"          "\n\t"
"STS   	1518, R10"       "\n\t"
"LDS   	R10, 1057"       "\n\t"
"BLD   	R5, 7"           "\n\t"
"STS   	1899, R20"       "\n\t"
"SUB   	R16, R17"        "\n\t"
"SUB   	R29, R29"        "\n\t"
"SBRS  	R12, 7"          "\n\t"
"CPI   	R27, 80"         "\n\t"
"OUT   	52, R14"         "\n\t"
"MUL   	R2, R7"          "\n\t"
"ROR   	R16"             "\n\t"
"BCLR  	2"               "\n\t"
"SUB   	R25, R10"        "\n\t"
"SBCI  	R25, 29"         "\n\t"
"BSET  	4"               "\n\t"
"SBCI  	R31, 223"        "\n\t"
"NEG   	R10"             "\n\t"
"LD    	R3, X+"          "\n\t"
"CPSE  	R15, R23"        "\n\t"
"SER   	R29"             "\n\t"
"AND   	R28, R22"        "\n\t"
"ADIW  	R26, 43"         "\n\t"
"SBRS  	R15, 7"          "\n\t"
"ADIW  	R24, 47"         "\n\t"
"BLD   	R24, 7"          "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"LPM   	"                "\n\t"
"LDD   	R25, Y+3"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"PUSH  	R19"             "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"OR    	R1, R10"         "\n\t"
"OUT   	30, R7"          "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"SBIS  	30, 7"           "\n\t"
"LDI   	R18, 28"         "\n\t"
"MULS  	R19, R20"        "\n\t"
"MULSU 	R17, R22"        "\n\t"
"OUT   	9, R16"          "\n\t"
"LSR   	R12"             "\n\t"
"ANDI  	R20, 151"        "\n\t"
"STS   	632, R30"        "\n\t"
"ROR   	R14"             "\n\t"
"SBRC  	R21, 5"          "\n\t"
"POP   	R1"              "\n\t"
"ADD   	R29, R2"         "\n\t"
"MULS  	R27, R17"        "\n\t"
"LD    	R23, X+"         "\n\t"
"MULS  	R17, R17"        "\n\t"
"SUBI  	R23, 47"         "\n\t"
"LDI   	R16, 147"        "\n\t"
"FMULSU	R21, R23"        "\n\t"
"FMUL  	R18, R22"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"PUSH  	R13"             "\n\t"
"SBC   	R17, R5"         "\n\t"
"CP    	R17, R22"        "\n\t"
"CPSE  	R27, R14"        "\n\t"
"SBC   	R30, R4"         "\n\t"
"ADIW  	R24, 50"         "\n\t"
"SBI   	5, 5"            "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"OUT   	14, R7"          "\n\t"
"LSR   	R31"             "\n\t"
"PUSH  	R6"              "\n\t"
"MULSU 	R23, R18"        "\n\t"
"ANDI  	R28, 123"        "\n\t"
"CALL  	Test_CALL"       "\n\t"
"NEG   	R21"             "\n\t"
"ST    	X+, R8"          "\n\t"
"SBIS  	3, 6"            "\n\t"
"POP   	R10"             "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CBI   	0, 1"            "\n\t"
"LDS   	R23, 538"        "\n\t"
"IN    	R22, 19"         "\n\t"
"OUT   	13, R28"         "\n\t"
"COM   	R22"             "\n\t"
"OR    	R6, R15"         "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"ANDI  	R21, 150"        "\n\t"
"SBI   	19, 6"           "\n\t"
"SBIC  	14, 1"           "\n\t"
"CP    	R29, R13"        "\n\t"
"SBCI  	R25, 68"         "\n\t"
"BSET  	1"               "\n\t"
"COM   	R21"             "\n\t"
"CPSE  	R14, R25"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"FMULS 	R20, R22"        "\n\t"
"LDI   	R24, 151"        "\n\t"
"SUB   	R4, R3"          "\n\t"
"ROR   	R23"             "\n\t"
"ANDI  	R22, 199"        "\n\t"
"PUSH  	R28"             "\n\t"
"FMUL  	R17, R23"        "\n\t"
"ADIW  	R28, 27"         "\n\t"
"FMULS 	R20, R18"        "\n\t"
"ORI   	R30, 55"         "\n\t"
"OUT   	43, R6"          "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CALL  	Test_JMP"        "\n\t"
"ADD   	R30, R21"        "\n\t"
"SUBI  	R25, 79"         "\n\t"
"SBIS  	28, 3"           "\n\t"
"LD    	R17, X"          "\n\t"
"SWAP  	R31"             "\n\t"
"CPI   	R19, 74"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"PUSH  	R24"             "\n\t"
"ASR   	R27"             "\n\t"
"FMULSU	R19, R17"        "\n\t"
"CP    	R11, R4"         "\n\t"
"LD    	R2, Y"           "\n\t"
"MULS  	R28, R24"        "\n\t"
"ST    	-Z, R20"         "\n\t"
"AND   	R11, R20"        "\n\t"
"NEG   	R7"              "\n\t"
"ADIW  	R28, 46"         "\n\t"
"BST   	R20, 7"          "\n\t"
"BSET  	2"               "\n\t"
"CPI   	R16, 67"         "\n\t"
"ROR   	R15"             "\n\t"
"ADD   	R30, R4"         "\n\t"
"STS   	1330, R21"       "\n\t"
"CPC   	R11, R25"        "\n\t"
"IN    	R10, 18"         "\n\t"
"LDS   	R1, 1783"        "\n\t"
"IN    	R24, 25"         "\n\t"
"ADC   	R16, R12"        "\n\t"
"CPC   	R25, R7"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"LDD   	R15, Z+54"       "\n\t"
"ANDI  	R23, 81"         "\n\t"
"NEG   	R22"             "\n\t"
"BCLR  	6"               "\n\t"
"SBI   	27, 6"           "\n\t"
"LD    	R6, -X"          "\n\t"
"SBCI  	R25, 73"         "\n\t"
"CALL  	Test_JMP"        "\n\t"
"OR    	R25, R22"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"MULS  	R17, R30"        "\n\t"
"CBI   	20, 3"           "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"BCLR  	1"               "\n\t"
"CALL  	Test_JMP"        "\n\t"
"EOR   	R10, R26"        "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
"SBI   	10, 4"           "\n\t"
"LSR   	R23"             "\n\t"
"SBIS  	4, 7"            "\n\t"
"FMULS 	R16, R21"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CBI   	7, 0"            "\n\t"
"LPM   	"                "\n\t"
"CBI   	27, 6"           "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"ADD   	R15, R0"         "\n\t"
"LPM   	R3, Z"           "\n\t"
"BST   	R5, 0"           "\n\t"
"LSR   	R14"             "\n\t"
"LDS   	R16, 680"        "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"CP    	R13, R8"         "\n\t"
"MOVW  	R22, R18"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBRC  	R2, 2"           "\n\t"
"LPM   	R19, Z+"         "\n\t"
"SER   	R16"             "\n\t"
"CP    	R30, R4"         "\n\t"
"COM   	R6"              "\n\t"
"CPSE  	R8, R18"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"CP    	R29, R1"         "\n\t"
"LPM   	R24, Z+"         "\n\t"
"LPM   	"                "\n\t"
"STD   	Y+52, R2"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"CPC   	R16, R7"         "\n\t"
"ASR   	R16"             "\n\t"
"OUT   	57, R18"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"CP    	R20, R6"         "\n\t"
"MUL   	R3, R28"         "\n\t"
"ADC   	R25, R18"        "\n\t"
"SBCI  	R24, 17"         "\n\t"
"SBIS  	18, 6"           "\n\t"
"SBCI  	R18, 31"         "\n\t"
"ADIW  	R24, 32"         "\n\t"
"LDD   	R22, Y+30"       "\n\t"
"CP    	R6, R10"         "\n\t"
"LSR   	R11"             "\n\t"
"MULSU 	R16, R17"        "\n\t"
"CP    	R28, R4"         "\n\t"
"CP    	R21, R4"         "\n\t"
"LPM   	R20, Z+"         "\n\t"
"CPC   	R12, R7"         "\n\t"
"SBC   	R8, R29"         "\n\t"
"ADD   	R28, R26"        "\n\t"
"COM   	R7"              "\n\t"
"MOV   	R27, R13"        "\n\t"
"SUBI  	R25, 151"        "\n\t"
"SBCI  	R18, 209"        "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"SER   	R30"             "\n\t"
"MUL   	R23, R23"        "\n\t"
"SBIC  	19, 0"           "\n\t"
"SBI   	5, 0"            "\n\t"
"FMUL  	R21, R16"        "\n\t"
"SBC   	R21, R18"        "\n\t"
"SBRS  	R28, 7"          "\n\t"
"BSET  	6"               "\n\t"
"CPC   	R12, R27"        "\n\t"
"BLD   	R28, 1"          "\n\t"
"SER   	R25"             "\n\t"
"ADC   	R31, R11"        "\n\t"
"EOR   	R29, R17"        "\n\t"
"MOVW  	R8, R30"         "\n\t"
"BLD   	R24, 1"          "\n\t"
"CALL  	Test_CALL"       "\n\t"
"OUT   	59, R7"          "\n\t"
"MULSU 	R20, R16"        "\n\t"
"LPM   	R0, Z"           "\n\t"
"LPM   	R20, Z+"         "\n\t"
"SUB   	R26, R23"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"FMULSU	R22, R17"        "\n\t"
"AND   	R18, R8"         "\n\t"
"BCLR  	1"               "\n\t"
"BCLR  	5"               "\n\t"
"SBIC  	5, 4"            "\n\t"
"ADD   	R20, R26"        "\n\t"
"MUL   	R23, R17"        "\n\t"
"COM   	R31"             "\n\t"
"SUBI  	R16, 219"        "\n\t"
"SBIC  	9, 2"            "\n\t"
"CALL  	Test_ICALL"      "\n\t"
"BSET  	0"               "\n\t"
"PUSH  	R31"             "\n\t"
"LPM   	R5, Z+"          "\n\t"
"SBRC  	R19, 4"          "\n\t"
"CPC   	R6, R7"          "\n\t"
"SBCI  	R19, 191"        "\n\t"
"LSR   	R16"             "\n\t"
"BCLR  	1"               "\n\t"
"SUBI  	R17, 134"        "\n\t"
"CBI   	27, 7"           "\n\t"
"SUBI  	R24, 232"        "\n\t"
"NEG   	R14"             "\n\t"
"CBI   	8, 6"            "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CALL  	Test_RCALL"      "\n\t"
"LPM   	R16, Z+"         "\n\t"
"OR    	R5, R28"         "\n\t"
"CPSE  	R16, R24"        "\n\t"
"ADD   	R2, R5"          "\n\t"
"CALL  	Test_CALL"       "\n\t"
"SBIC  	27, 3"           "\n\t"
"LPM   	R18, Z"          "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"STS   	1324, R29"       "\n\t"
"LDD   	R21, Y+9"        "\n\t"
"ADC   	R6, R2"          "\n\t"
"COM   	R17"             "\n\t"
"FMULS 	R18, R17"        "\n\t"
"LDS   	R17, 894"        "\n\t"
"SER   	R30"             "\n\t"
"ASR   	R7"              "\n\t"
"OR    	R3, R26"         "\n\t"
"EOR   	R19, R2"         "\n\t"
"BST   	R17, 1"          "\n\t"
"OUT   	41, R3"          "\n\t"
"COM   	R10"             "\n\t"
"ADIW  	R28, 11"         "\n\t"
"IN    	R6, 63"          "\n\t"
"MULSU 	R23, R17"        "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"ORI   	R30, 127"        "\n\t"
"SBCI  	R20, 13"         "\n\t"
"IN    	R27, 24"         "\n\t"
"CALL  	Test_IJMP"       "\n\t"
"NEG   	R20"             "\n\t"
"SWAP  	R31"             "\n\t"
"PUSH  	R13"             "\n\t"
"SBRC  	R3, 6"           "\n\t"
"LPM   	R28, Z"          "\n\t"
"SBRS  	R21, 1"          "\n\t"
"CALL  	Test_BRBC"       "\n\t"
"CP    	R22, R16"        "\n\t"
"LDD   	R23, Z+47"       "\n\t"
"ASR   	R12"             "\n\t"
"MUL   	R11, R11"        "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"OUT   	62, R17"         "\n\t"
"SBCI  	R18, 122"        "\n\t"
"MOV   	R10, R30"        "\n\t"
"SER   	R21"             "\n\t"
"LD    	R8, Y"           "\n\t"
"LDS   	R28, 1153"       "\n\t"
"ST    	Y+, R23"         "\n\t"
"ADD   	R3, R17"         "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"OUT   	47, R15"         "\n\t"
"ASR   	R17"             "\n\t"
"AND   	R30, R19"        "\n\t"
"CALL  	Test_BRBS"       "\n\t"
"STD   	Z+25, R26"       "\n\t"
"OR    	R0, R12"         "\n\t"
"ANDI  	R23, 255"        "\n\t"
"ROR   	R27"             "\n\t"
"FMULS 	R17, R17"        "\n\t"
"CBI   	9, 4"            "\n\t"
"CPI   	R22, 34"         "\n\t"
"SBIS  	7, 6"            "\n\t"
"COM   	R30"             "\n\t"
"SUB   	R23, R28"        "\n\t"
"CPI   	R18, 0"          "\n\t"
"AND   	R8, R10"         "\n\t"
"ASR   	R12"             "\n\t"
"ORI   	R19, 193"        "\n\t"
"MULS  	R17, R29"        "\n\t"
"BST   	R8, 7"           "\n\t"
"ORI   	R27, 92"         "\n\t"
"BST   	R1, 1"           "\n\t"
"SUB   	R4, R0"          "\n\t"
"SBCI  	R19, 235"        "\n\t"
"SBRS  	R2, 6"           "\n\t"
"MULSU 	R23, R19"        "\n\t"
"SER   	R30"             "\n\t"
"ADD   	R30, R25"        "\n\t"
"ADC   	R10, R24"        "\n\t"
"CALL  	Test_JMP"        "\n\t"
"IN    	R31, 17"         "\n\t"
"LPM   	"                "\n\t"
"OR    	R9, R24"         "\n\t"
"CALL  	Test_RJMP"       "\n\t"
"SBIS  	31, 6"           "\n\t"
"LPM   	"                "\n\t"
"CPI   	R18, 115"        "\n\t"
"STD   	Y+9, R16"        "\n\t"
"ADC   	R8, R29"         "\n\t"
"SBCI  	R20, 58"         "\n\t"
"CALL  	Test_CALL"       "\n\t"
"ADIW  	R30, 34"         "\n\t"
"LDD   	R17, Z+20"       "\n\t"
"NOP"                    "\n\t"
"CALL	CRC_REGISTERS%=" "\n\t"
"CALL	DUMP_REGS%="     "\n\t"
