// ".equ CRCL, 0x0400" "\n\t"
// ".equ SPL, 0x3D" "\n\t" // io address 0x5D for mem addr
// ".equ SPH, 0x3E" "\n\t" // io address 0x5E for mem addr
// ".equ SREG, 0x3F" "\n\t" // io address 0x5F for mem addr
// ".equ CRCH, 0x0401" "\n\t"
// ".equ FUNCTIONS, 0x01000" "\n\t"
// ".equ REGVEC , 0x400" "\n\t"
/*".equ REGPTR , 0x200" "\n\t"*/

//".DSEG \n\t"
// "REGVEC: .byte 0xFF \n\t"
// "REGPTR: .byte 2" "\n\t"
//".CSEG \n\t"
".org FUNCTIONS \n\t"

// GUARD BAND
"STOP_IT%=:" "\n\t"
  "NOP" "\n\t"
  "RJMP STOP_IT%=" "\n\t"

"DUMP_REGS%=: \n\t"
"PUSH ZL \n\t"
"PUSH ZH \n\t"
"PUSH YL \n\t"
"PUSH YH \n\t"
"PUSH XL \n\t"
"PUSH XH \n\t"
"LDS ZL, REGVEC"  "\n\t"
"LDS ZH, REGVEC+1"  "\n\t"
"LDI YH, 0 \n\t"
"LDI YL, 0 \n\t"
"LDI XH, 26 \n\t"
"LOOP_DUMP_REG%=:"
"LD XL,Y+ \n\t"
"ST Z+, XL \n\t"
"DEC XH \n\t"
"BRNE LOOP_DUMP_REG%= \n\t"
"POP XH \n\t"
"POP XL \n\t"
"POP YH \n\t"
"POP YL \n\t"
"ST Z+, XL \n\t"
"ST Z+, XH \n\t"
"ST Z+, YL \n\t"
"ST Z+, YH \n\t"
"POP YH \n\t"
"POP YL \n\t"
"ST Z+, YL \n\t"
"ST Z+, YH \n\t"
"CALL next_instruction%=" "\n\t"
"next_instruction%=:" "\n\t"
"POP R17" "\n\t"
"POP R16" "\n\t"
"ST Z+, R16" "\n\t"
"ST Z+, R17" "\n\t"
"IN R16, SPL" "\n\t"
"IN R17, SPH" "\n\t"
"ST Z+, R16" "\n\t"
"ST Z+, R17" "\n\t"
"IN R16, SREG" "\n\t"
"ST Z+, R16" "\n\t"
"STS REGVEC, ZL" "\n\t"
"STS REGVEC+1, ZH" "\n\t"
"RET \n\t"

"Test_JMP:""\n\t"
	"jmp L4_%=" "\n\t"
"L2_%=:""\n\t"
	"jmp L5_%=" "\n\t"
"L3_%=:""\n\t"
	"nop" "\n\t"
	"jmp L6_%=" "\n\t"
"L4_%=:""\n\t"
	"jmp L2_%=" "\n\t"
"L5_%=:""\n\t"
	"jmp L3_%=" "\n\t"
	"nop" "\n\t"
	"nop" "\n\t"
"L6_%=:\n\t"
   "ret \n\t"

"Test_IJMP:""\n\t"
  "ldi ZH, pm_hi8(L4_IJ%=)" "\n\t"
  "ldi ZL, pm_lo8(L4_IJ%=)" "\n\t"
   "ijmp" "\n\t"
"L2_IJ%=:""\n\t"
  "ldi ZH, pm_hi8(L5_IJ%=)" "\n\t"
  "ldi ZL, pm_lo8(L5_IJ%=)" "\n\t"
  "ijmp" "\n\t"
"L3_IJ%=:""\n\t"
  "nop" "\n\t"
  "ldi ZH, pm_hi8(L6_IJ%=)" "\n\t"
  "ldi ZL, pm_lo8(L6_IJ%=)" "\n\t"
  "ijmp" "\n\t"
"L4_IJ%=:""\n\t"
  "ldi ZH, pm_hi8(L2_IJ%=)" "\n\t"
  "ldi ZL, pm_lo8(L2_IJ%=)" "\n\t"
	"ijmp" "\n\t"
"L5_IJ%=:""\n\t"
	"nop" "\n\t"
	"nop" "\n\t"
  "ldi ZH, pm_hi8(L3_IJ%=)" "\n\t"
  "ldi ZL, pm_lo8(L3_IJ%=)" "\n\t"
	"ijmp" "\n\t"
"L6_IJ%=:"  
  "RET \n\t"

"Test_RJMP:""\n\t"
	"rjmp L4_RJ%=" "\n\t"
"L2_RJ%=:""\n\t"
	"rjmp L5_RJ%=" "\n\t"
"L3_RJ%=:""\n\t"
	"nop" "\n\t"
	"rjmp L6_RJ%=" "\n\t"
"L4_RJ%=:""\n\t"
	"rjmp L2_RJ%=" "\n\t"
"L5_RJ%=:""\n\t"
	"rjmp L3_RJ%=" "\n\t"
	"nop" "\n\t"
	"nop" "\n\t"
"L6_RJ%=:"
  "RET \n\t"  

"Test_CALL:""\n\t"
	"call L4_C%=" "\n\t"
"L2_C%=:""\n\t"
	"call L5_C%=" "\n\t"
	"rjmp L7_C%=" "\n\t"
"L3_C%=:""\n\t"
	"nop" "\n\t"
	"rjmp L6_C%=" "\n\t"
"L4_C%=:""\n\t"
	"rcall L6_C%=" "\n\t"
	"ret" "\n\t"
"L5_C%=:""\n\t"
	"rjmp L3_C%=" "\n\t"
	"nop" "\n\t"
	"nop" "\n\t"
"L6_C%=:""\n\t"
	"ret" "\n\t"
"L7_C%=:" "\n\t"
  "RET \n\t"

"Test_ICALL:""\n\t"
  "ldi ZH, pm_hi8(L4_IC%=)" "\n\t"
  "ldi ZL, pm_lo8(L4_IC%=)" "\n\t"
   "icall" "\n\t"
   "rjmp L5_IC%=" "\n\t"
"L2_IC%=:""\n\t"
  "PUSH __tmp_reg__" "\n\t"
  "POP __tmp_reg__" "\n\t"
  "ret" "\n\t"
"L3_IC%=:""\n\t"
  "nop" "\n\t"
  "ldi ZH, pm_hi8(L6_IC%=)" "\n\t"
  "ldi ZL, pm_lo8(L6_IC%=)" "\n\t"
  "ijmp" "\n\t"
"L4_IC%=:""\n\t"
  "ldi ZH, pm_hi8(L2_IC%=)" "\n\t"
  "ldi ZL, pm_lo8(L2_IC%=)" "\n\t"
	"icall" "\n\t"
  "ret" "\n\t"
"L5_IC%=:""\n\t"
	"nop" "\n\t"
	"nop" "\n\t"
  "ldi ZH, pm_hi8(L4_IC%=)" "\n\t"
  "ldi ZL, pm_lo8(L4_IC%=)" "\n\t"
	"icall" "\n\t"
"L6_IC%=:" "\n\t"
  "ret" "\n\t"

"Test_RCALL:""\n\t"
	"call L4_RC%=" "\n\t"
"L2_RC%=:""\n\t"
	"call L5_RC%=" "\n\t"
	"rjmp L7_RC%=" "\n\t"
"L3_RC%=:""\n\t"
	"nop" "\n\t"
	"rjmp L6_RC%=" "\n\t"
"L4_RC%=:""\n\t"
	"rcall L6_RC%=" "\n\t"
	"ret" "\n\t"
"L5_RC%=:""\n\t"
	"rjmp L3_RC%=" "\n\t"
	"nop" "\n\t"
	"nop" "\n\t"
"L6_RC%=:""\n\t"
	"ret" "\n\t"
"L7_RC%=:" "\n\t"
  "RET \n\t"
  

"Test_BRBS:""\n\t"
  "SEC"   "\n\t"
  "SEN"   "\n\t"
  "SEZ"   "\n\t"
  "SEI"   "\n\t"
  "SES"   "\n\t"
  "SEV"   "\n\t"
  "SET"   "\n\t"
  "SEH"   "\n\t"
  "RJMP CK2" "\n\t"
"CK1: \n\t"
  "CLC"   "\n\t"
"CK2:"  "\n\t"
  "BRCS CK1" "\n\t"
  "SEC" "\n\t"
  "BRCS CK3" "\n\t"
  "CLN"   "\n\t"
"CK3: \n\t"
  "RJMP CK5" "\n\t"
"CK4: \n\t"
  "CLN"   "\n\t"
"CK5:"  "\n\t"
  "BRMI CK4" "\n\t"
  "SEN" "\n\t"
  "BRMI CK6" "\n\t"
  "CLZ"   "\n\t"
"CK6: \n\t"
  "RJMP CK8" "\n\t"
"CK7: \n\t"
  "CLZ"   "\n\t"
"CK8:"  "\n\t"
  "BREQ CK7" "\n\t"
  "SEZ" "\n\t"
  "BREQ CK9" "\n\t"
  "CLI"   "\n\t"
"CK9: \n\t"  
  "RJMP CK11" "\n\t"
"CK10: \n\t"
  "CLI"   "\n\t"
"CK11:"  "\n\t"
  "BRIE CK10" "\n\t"
  "SEI" "\n\t"
  "BRIE CK12" "\n\t"
  "CLS"   "\n\t"  
"CK12:"  "\n\t"
  "RJMP CK14" "\n\t"
"CK13: \n\t"
  "CLS"   "\n\t"
"CK14:"  "\n\t"
  "BRLT CK13" "\n\t"
  "SES" "\n\t"
  "BRLT CK15" "\n\t"
  "CLV"   "\n\t"  
"CK15:"  "\n\t"
   "RJMP CK17" "\n\t"
"CK16: \n\t"
  "CLV"   "\n\t"
"CK17:"  "\n\t"
  "BRVS CK16" "\n\t"
  "SEV" "\n\t"
  "BRVS CK18" "\n\t"
  "CLS"   "\n\t"  
"CK18:"  "\n\t"
   "RJMP CK20" "\n\t"
"CK19: \n\t"
  "CLT"   "\n\t"
"CK20:"  "\n\t"
  "BRTS CK19" "\n\t"
  "SET" "\n\t"
  "BRTS CK21" "\n\t"
  "CLH"   "\n\t"  
"CK21:"  "\n\t"
   "RJMP CK23" "\n\t"
"CK22: \n\t"
  "CLH"   "\n\t"
"CK23:"  "\n\t"
  "BRHS CK22" "\n\t"
  "SEH" "\n\t"
  "BRHS CK24" "\n\t"
  "CLH"   "\n\t"  
"CK24:"  "\n\t"

  "RET \n\t" 



"Test_BRBC:""\n\t"
  "CLC"   "\n\t"
  "CLN"   "\n\t"
  "CLZ"   "\n\t"
  "CLI"   "\n\t"
  "CLS"   "\n\t"
  "CLV"   "\n\t"
  "CLT"   "\n\t"
  "CLH"   "\n\t"
  "RJMP SK2" "\n\t"
"SK1: \n\t"
  "SEC"   "\n\t"
"SK2:"  "\n\t"
  "BRCC SK1" "\n\t"
  "CLC" "\n\t"
  "BRCC SK3" "\n\t"
  "SEN"   "\n\t"
"SK3: \n\t"
  "RJMP SK5" "\n\t"
"SK4: \n\t"
  "SEN"   "\n\t"
"SK5:"  "\n\t"
  "BRPL SK4" "\n\t"
  "CLN" "\n\t"
  "BRPL SK6" "\n\t"
  "SEZ"   "\n\t"
"SK6: \n\t"
  "RJMP SK8" "\n\t"
"SK7: \n\t"
  "SEZ"   "\n\t"
"SK8:"  "\n\t"
  "BRNE SK7" "\n\t"
  "CLZ" "\n\t"
  "BRNE SK9" "\n\t"
  "SEI"   "\n\t"
"SK9: \n\t"  
  "RJMP SK11" "\n\t"
"SK10: \n\t"
  "SEI"   "\n\t"
"SK11:"  "\n\t"
  "BRID SK10" "\n\t"
  "CLI" "\n\t"
  "BRID SK12" "\n\t"
  "SES"   "\n\t"  
"SK12:"  "\n\t"
  "RJMP SK14" "\n\t"
"SK13: \n\t"
  "SES"   "\n\t"
"SK14:"  "\n\t"
  "BRGE SK13" "\n\t"
  "CLS" "\n\t"
  "BRGE SK15" "\n\t"
  "SEV"   "\n\t"  
"SK15:"  "\n\t"
   "RJMP SK17" "\n\t"
"SK16: \n\t"
  "SEV"   "\n\t"
"SK17:"  "\n\t"
  "BRVC SK16" "\n\t"
  "CLV" "\n\t"
  "BRVC SK18" "\n\t"
  "SET"   "\n\t"  
"SK18:"  "\n\t"
   "RJMP SK20" "\n\t"
"SK19: \n\t"
  "SET"   "\n\t"
"SK20:"  "\n\t"
  "BRTC SK19" "\n\t"
  "CLT" "\n\t"
  "BRTC SK21" "\n\t"
  "SEH"   "\n\t"  
"SK21:"  "\n\t"
   "RJMP SK23" "\n\t"
"SK22: \n\t"
  "SEH"   "\n\t"
"SK23:"  "\n\t"
  "BRHC SK22" "\n\t"
  "CLH" "\n\t"
  "BRHC SK24" "\n\t"
  "CLH"   "\n\t"  
"SK24:"  "\n\t"
  "RET \n\t" 

"CRC_REGISTERS%=: \n\t"
  "PUSH YH \n\t"
  "PUSH ZL \n\t"
  "PUSH ZH \n\t"
  "LDI YH, 28 \n\t"
  "LDI ZH, 0 \n\t"
  "LDI ZL, 1 \n\t"
"LOOP_REG%=:"  
  "LD R0, Z+ \n\t"
  "CALL CCITT16_CRC%=" "\n\t"
  "DEC YH \n\t"
  "BRNE LOOP_REG%= \n\t"
  "POP ZH \n\t"
  "POP ZL \n\t"
  "POP YH \n\t"
  "MOV R0, YH \n\t"
  "CALL CCITT16_CRC%=" "\n\t"  
  "MOV R0, ZL \n\t"
  "CALL CCITT16_CRC%=" "\n\t"  
  "MOV R0, ZH \n\t"
  "CALL CCITT16_CRC%=" "\n\t"  
  "RET \n\t"



// Data is @R0, CRC is @[CRCH:CRCL]
"CCITT16_CRC%=:" "\n\t"
  "PUSH R18 \n\t"
  "PUSH R19 \n\t"
  "PUSH R24 \n\t"
  "PUSH R25 \n\t"
//  "PUSH SREG \n\t"
  "LDS R24, CRCL" "\n\t"
  "LDS R25, CRCH" "\n\t"
  //L2//  CRC ^= (Data <<8);
  "EOR	R25, R0" "\n\t"
  // CRC is @R25:R24
  //L3//  for (int R18 = 8;  // R18==0 ; R18--)
  "LDI	R18,0x08" "\n\t"
"Label1%=:" "\n\t"//if (CRC[15]==1)
  "CLT \n\t"
  "SBRS	R25,7" "\n\t"
  "SET \n\t"
  // CRC <<=1
  "LSL	R24" "\n\t"
  "ROL	R25" "\n\t"
  "BRTC Label2%= \n\t" 
//L5// CRC = (CRC << 1) ^ 0x1021
  // CRC ^= 0x1021
  "LDI	R19,0x21" "\n\t"
  "EOR	R24,R19" "\n\t"
  "LDI	R19,0x10" "\n\t"
  "EOR	R25,R19" "\n\t"
"Label2%=:" "\n\t"
  //L3// R18-- if R18==0 finishes
  "SUBI	R18,0x01" "\n\t"
  // Branch if R18 != 0
  "BRNE	Label1%=" "\n\t"
"Fin%=:" "\n\t"
  "STS CRCL, R24" "\n\t"
  "STS CRCH, R25" "\n\t"
//  "POP SREG"
  "POP R25 \n\t"
  "POP R24 \n\t"
  "POP R19 \n\t"
  "POP R18 \n\t"
  "RET" "\n\t"